using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;
namespace CodexUsageMonitor;
internal static class HumanFixProbe {
 [DllImport("user32.dll")]static extern bool PrintWindow(IntPtr h,IntPtr dc,uint flags);
 static IEnumerable<Control> Tree(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in Tree(child))yield return x;}
 static void Frame(Form f,string p){using var b=new Bitmap(f.Width,f.Height);using(var g=Graphics.FromImage(b)){var dc=g.GetHdc();try{if(!PrintWindow(f.Handle,dc,2))throw new IOException("PrintWindow failed");}finally{g.ReleaseHdc(dc);}}b.Save(p);}
 internal static void Attach(OverlayForm overlay,MonitorService s,string[] args){int at=Array.IndexOf(args,"--human-fix-probe");if(at<0)return;if(!args.Contains("--synthetic-ui")||!s.Root.Contains("main-data",StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Isolated fixture required");string output=Path.GetFullPath(args[at+1]);Directory.CreateDirectory(output);var results=new List<object>();var errors=new List<string>();Application.ThreadException+=(_,e)=>{errors.Add(e.Exception.ToString());File.WriteAllText(Path.Combine(output,"thread-errors.txt"),string.Join("\n",errors));};
 overlay.Shown+=async(_,_)=>{try{
  var now=DateTimeOffset.UtcNow.AddMinutes(-5);var rows=Rc4HistoryEventTests.EvidenceRows(now).samples;rows.Add(Rc4HistoryEventTests.Sample("confirmation",now.AddSeconds(90),99,reset:now.AddDays(7)));
  // Dense independent fixture: preserve the exact replenishment pair while adding a week of observations.
  for(int i=0;i<1800;i++)rows.Add(Rc4HistoryEventTests.Sample("dense-"+i,now.AddDays(-6).AddMinutes(i*4),98-(i%90),reset:now.AddDays(7)));
  s.History.Save(rows);var last=rows.First(x=>x.sample_id=="confirmation");var snapshot=new Snapshot(now,now,0,last.account_context_key,last.context_assurance,last.source_generation,"synthetic",[new WindowQuota("codex","Codex",last.source_slot,10080,last.used_percent_raw,last.reset_at_utc!.Value.ToUnixTimeSeconds(),"VALID",last.plan_type,null,null,null,"")],1,[]);typeof(MonitorService).GetProperty("Current")!.SetValue(s,snapshot);s.MainClock.Observe(snapshot,s.Monotonic);s.Settings.ChartView="FULL";

  // Duplicate startup must hand back to this exact isolated writer, including Windows path aliases.
  foreach(string alias in new[]{s.Root,s.Root.ToLowerInvariant()+Path.DirectorySeparatorChar}){var start=new ProcessStartInfo(Environment.ProcessPath!){UseShellExecute=false,CreateNoWindow=true};start.ArgumentList.Add("--synthetic-ui");start.ArgumentList.Add("--data-root");start.ArgumentList.Add(alias);using var child=Process.Start(start)!;await child.WaitForExitAsync().WaitAsync(TimeSpan.FromSeconds(7));results.Add(new{test="duplicate-alias",same_writer=RuntimeIdentity.Existing(s.Root)?.Pid==Environment.ProcessId,exit_code=child.ExitCode});}
  var standard=Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)+@"\CodexUsageMonitor";results.Add(new{test="scope-provider-equivalent",same=s.Radar.VerifiedLocalScopes!().SequenceEqual(UsageSample.From(snapshot,false,s.Settings.Interval).Where(x=>x.limit_id=="codex"&&x.window_duration_mins==10080).Select(LocalQuotaCycle.Scope))});results.Add(new{test="default-legacy-mutex-compatible",same=RuntimeIdentity.CanonicalRoot(standard)==standard&&RuntimeIdentity.CanonicalRoot(standard.ToLowerInvariant()+"\\")==standard});
  var menu=(ContextMenuStrip)typeof(OverlayForm).GetField("menu",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(overlay)!;
  foreach(string lang in new[]{"zh-TW","en-US"}){L.SetLanguage(lang);foreach(string key in new[]{"Menu.Details","Menu.History","Menu.Reset","Menu.Settings","Menu.About","Menu.Details","Menu.Reset"}){
   ProductForm? page=null;long layouts=0,paints=0,sizes=0;var sw=Stopwatch.StartNew();ProductForm.PresentationObserved=f=>{page=f;foreach(var c in Tree(f)){c.Layout+=(_,_)=>layouts++;c.Paint+=(_,_)=>paints++;c.SizeChanged+=(_,_)=>sizes++;}};
   overlay.BeginInvoke((Action)(()=>{try{menu.Items.OfType<ToolStripMenuItem>().First(x=>x.Text==L.T(key)).PerformClick();}catch(Exception e){errors.Add(key+": "+e);}}));
   while((page==null||!page.Visible)&&sw.ElapsedMilliseconds<6000)await Task.Delay(25);ProductForm.PresentationObserved=null;
   if(page==null||!page.Visible){results.Add(new{key,lang,opened=false,errors=errors.ToArray()});continue;}
   await Task.Delay(800);var f=page;long beforeL=layouts,beforeP=paints,beforeS=sizes;long alloc=GC.GetTotalAllocatedBytes();var cpu=Process.GetCurrentProcess().TotalProcessorTime;await Task.Delay(700);
   results.Add(new{key,lang,opened=true,dpi=f.DeviceDpi,width=f.Width,height=f.Height,open_ms=sw.ElapsedMilliseconds,idle_layout=layouts-beforeL,idle_paint=paints-beforeP,idle_size=sizes-beforeS,idle_alloc=GC.GetTotalAllocatedBytes()-alloc,idle_cpu_ms=(Process.GetCurrentProcess().TotalProcessorTime-cpu).TotalMilliseconds});
   var original=f.Size;f.Size=new(Math.Max(f.MinimumSize.Width,f.Width-170),Math.Max(450,f.Height-70));await Task.Delay(180);f.Size=original;await Task.Delay(180);
   if(f is DetailsForm){var chosen=new Size(f.Width+24,f.Height-20);f.Size=chosen;beforeS=sizes;for(int i=0;i<12;i++)((Action?)typeof(MonitorService).GetField("Changed",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(s))?.Invoke();await Task.Delay(300);results.Add(new{key,lang,refresh_kept_size=f.Size==chosen,refresh_size_events=sizes-beforeS});foreach(var b in Tree(f).OfType<Button>().Where(b=>b.Text==L.T("Details.OtherPools")||b.Text==L.T("Details.Advanced")).ToArray()){b.PerformClick();await Task.Delay(120);b.PerformClick();await Task.Delay(120);} results.Add(new{key,lang,test="details-folded",states=Tree(f).OfType<Label>().Where(x=>x.Text.Contains("app-server")).Select(x=>new{x.Visible,x.Height,x.Top}).ToArray()});
    typeof(MonitorService).GetProperty("Current")!.SetValue(s,snapshot with {Windows=[..snapshot.Windows,new WindowQuota("spark","Spark","secondary",300,12,0,"VALID","",null,null,null,"")],CreditExpirations=[long.MaxValue]});((Action?)typeof(MonitorService).GetField("Changed",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(s))?.Invoke();await Task.Delay(120);
    typeof(MonitorService).GetProperty("Current")!.SetValue(s,null);((Action?)typeof(MonitorService).GetField("Changed",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(s))?.Invoke();await Task.Delay(120);typeof(MonitorService).GetProperty("Current")!.SetValue(s,snapshot);((Action?)typeof(MonitorService).GetField("Changed",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(s))?.Invoke();await Task.Delay(120); }
   if(f is HistoryForm h){h.SetChartMode(false);await Task.Delay(150);var grid=Tree(f).OfType<R2Grid>().Single();alloc=GC.GetTotalAllocatedBytes();sw.Restart();for(int i=0;i<30;i++){grid.Invalidate(new Rectangle(grid.Width-20,0,20,grid.Height));grid.Update();}results.Add(new{key,lang,thirty_grid_paints_ms=sw.Elapsed.TotalMilliseconds,thirty_grid_alloc=GC.GetTotalAllocatedBytes()-alloc,rows=grid.Rows.Count});var apply=Tree(f).OfType<Button>().First(x=>x.Text==L.T("History.Apply"));apply.PerformClick();await Task.Delay(400);
    var rail=Tree(f).OfType<GoldEventRail>().Single();var body=Tree(f).OfType<SpacePanel>().Single();var tr=h.TrendForTest;
    f.MinimumSize=new(760,560);foreach(int width in new[]{1680,1140,760}){f.Width=width;await Task.Delay(120);body.ScrollControlIntoView(tr);await Task.Delay(160);tr.ZoomFullAt(.4,true);tr.PanFull(.3);tr.ResetViewport();tr.StepGold(1);await Task.Delay(80);var rb=rail.RectangleToScreen(rail.ClientRectangle);var tb=tr.RectangleToScreen(tr.ClientRectangle);var overlap=Rectangle.Intersect(rb,tb);bool chartContained=tr.Bottom<=tr.Parent!.ClientSize.Height-tr.Parent.Padding.Bottom;var buttons=rail.Controls.Cast<Control>().ToArray();bool buttonsSeparate=!buttons.SelectMany((a,i)=>buttons.Skip(i+1).Select(b=>Rectangle.Intersect(a.Bounds,b.Bounds))).Any(b=>b.Width>0&&b.Height>0);results.Add(new{key,lang,test="rail-geometry",width=f.Width,rail_width=rail.Width,rail_height=rail.Height,intersection_area=overlap.Width*overlap.Height,buttonsSeparate,chartContained});f.Refresh();Frame(f,Path.Combine(output,"rail-"+lang+"-"+width+".png"));}
    f.Size=original;body.AutoScrollPosition=Point.Empty;await Task.Delay(150);
    int builds=grid.BackdropBuilds;for(int i=0;i<10;i++){grid.Invalidate();grid.Update();}results.Add(new{key,lang,test="backdrop-reuse",rebuilds=grid.BackdropBuilds-builds});body.AutoScrollPosition=new(0,80);grid.Invalidate();grid.Update();results.Add(new{key,lang,test="backdrop-scroll-dirty",rebuilt=grid.BackdropBuilds>builds});body.AutoScrollPosition=Point.Empty;
    using(var exported=new ExportForm(s,h.ExportRange)){exported.Show(f);await Task.Delay(150);results.Add(new{key,lang,test="export-open",visible=exported.Visible});exported.Close();}

    if(tr.RailEvent is {} selectedEvent){tr.OpenGold(selectedEvent.id);await Task.Delay(150);results.Add(new{key,lang,test="rail-click-focus",matched=h.FocusEvidence?.LocalCycle?.id==selectedEvent.id,focus=h.IsEventFocusVisible});h.SetChartMode(false);}
    var windowChoice=(DarkChoice)typeof(HistoryForm).GetField("window",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(h)!;windowChoice.SelectedIndex=1;var filterWait=Stopwatch.StartNew();while(h.ExportRange.Duration!=300&&filterWait.ElapsedMilliseconds<4000)await Task.Delay(25);if(h.ExportRange.Duration!=300)throw new InvalidOperationException("Five-hour query did not complete");if(tr.RailEvent is {} weekly){tr.OpenGold(weekly.id);await Task.Delay(100);results.Add(new{key,lang,test="rail-focus-under-five-hour-filter",duration=h.ExportRange.Duration,matched=h.FocusEvidence?.LocalCycle?.id==weekly.id,focus=h.IsEventFocusVisible});h.SetChartMode(false);}else throw new InvalidOperationException("Missing weekly rail fixture");windowChoice.SelectedIndex=0;await Task.Delay(350);

   }
   await Task.Delay(200);f.Refresh();
   Frame(f,Path.Combine(output,key+"-"+lang+".png"));f.Close();await Task.Delay(60);AtomicJson.Save(Path.Combine(output,"probe.json"),new{results,errors,dense_samples=rows.Count});
  }}
 }catch(Exception e){errors.Add(e.ToString());}finally{AtomicJson.Save(Path.Combine(output,"probe.json"),new{results,errors,build=RuntimeIdentity.Build,exe_sha256=RuntimeIdentity.Hash(Environment.ProcessPath!)});ProductForm.PresentationObserved=null;overlay.Close();}};
 }
}
