using System.Text.Json;
namespace CodexUsageMonitor;

internal static class Rc4ActiveUnreadTests {
 static void Assert(bool value,string id){if(!value)throw new InvalidOperationException(id);}
 internal static void Run(string root){Directory.CreateDirectory(root);var results=new List<object>();int failed=0;var now=DateTimeOffset.UtcNow;
  void Check(string id,Action action){try{action();results.Add(new{id,result="PASS",classification="FOCUSED_PRODUCTION_PATH"});}catch(Exception ex){failed++;results.Add(new{id,result="FAIL",classification="FOCUSED_PRODUCTION_PATH",error=ex.ToString()});}}
  Announcement Watch(string id)=>Rc4SignalPolishTests.Signal("WATCH",id);
  Announcement Incoming(string id)=>Rc4SignalPolishTests.Signal("INCOMING",id);
  Check("T01 no event has no active dot",()=>{using var service=new MonitorService(Path.Combine(root,"t01"));service.Settings.Compact=true;using var overlay=new OverlayForm(service,true);overlay.Render();Assert(service.Radar.ActiveSignal==null&&service.Radar.ActiveSignalLevel=="NONE"&&!overlay.RadarSignalUnread,"no active signal");});
  Check("T02 WATCH unread is active attention",()=>{using var radar=new ResetRadar(Path.Combine(root,"t02"));var item=Watch("6000000000000000002");radar.Apply([item],now);Assert(radar.ActiveSignal?.SignalLevel=="WATCH"&&radar.ActiveSignal?.ReadAt==null&&radar.Unread!=null,"watch unread");});
  Check("T03 opening WATCH removes attention but keeps active",()=>{using var radar=new ResetRadar(Path.Combine(root,"t03"));var item=Watch("6000000000000000003");radar.Apply([item],now);radar.Read(item.EventId,item.RevisionId);Assert(radar.ActiveSignal?.SignalLevel=="WATCH"&&radar.ActiveSignal?.ReadAt!=null&&radar.Unread==null,"watch read active");});
  Check("T04 restart preserves read active WATCH",()=>{string dir=Path.Combine(root,"t04");var item=Watch("6000000000000000004");using(var radar=new ResetRadar(dir)){radar.Apply([item],now);radar.Read(item.EventId,item.RevisionId);}using var restored=new ResetRadar(dir);Assert(restored.ActiveSignal?.SignalLevel=="WATCH"&&restored.ActiveSignal?.ReadAt!=null&&restored.Unread==null,"restart read active");});
  Check("T05 TEAM WATCH stays coherent through 49h and expires after 72h",()=>{string dir=Path.Combine(root,"t05");var item=Watch("6000000000000000005") with{PublishedAt=now.AddHours(-49),FirstSeen=now.AddHours(-49),LastSeen=now.AddHours(-49),ReadAt=now.AddHours(-48)};var state=new RadarState{Events=[item]};Assert(ResetRadar.ActiveSignalAt(item,state,now),"49h team watch active");Assert(!ResetRadar.ActiveSignalAt(item,state,now.AddHours(24)),"73h team watch expired");AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);using var service=new MonitorService(dir);using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);Assert(service.Radar.ActiveSignal?.SignalLevel=="WATCH"&&page.DisplayedRadarStatus==L.T("Radar.StatusWatch")&&page.DisplayedActiveSignalRows==1,"page agrees with active dot at 49h");});
  Check("T06 major WATCH revision restores unread attention",()=>{using var radar=new ResetRadar(Path.Combine(root,"t06"));var item=Watch("6000000000000000006");radar.Apply([item],now);radar.Read(item.EventId,item.RevisionId);var revision=item with{Scope="ALL",RevisionId="major-watch-revision",ContentHash="major-watch-content"};radar.Apply([revision],now.AddHours(71));var active=radar.ActiveSignalsAt(now.AddHours(72)).Single();Assert(active.SignalLevel=="WATCH"&&active.ReadAt==null&&radar.Snapshot().Transitions.Count==1,"major revision unread and relevance reset");});
  Check("T07 WATCH to INCOMING becomes red unread attention",()=>{using var radar=new ResetRadar(Path.Combine(root,"t07"));var watch=Watch("6000000000000000007");radar.Apply([watch],now);radar.Read(watch.EventId,watch.RevisionId);var incoming=Incoming("6000000000000000007");radar.Apply([incoming],now.AddMinutes(1));Assert(radar.ActiveSignal?.SignalLevel=="INCOMING"&&radar.ActiveSignal?.ReadAt==null&&radar.Snapshot().Transitions.Any(x=>x.FromSignal=="WATCH"&&x.ToSignal=="INCOMING"),"incoming unread");});
  Check("T08 opening INCOMING keeps red active signal",()=>{using var radar=new ResetRadar(Path.Combine(root,"t08"));var item=Incoming("6000000000000000008");radar.Apply([item],now);radar.Read(item.EventId,item.RevisionId);Assert(radar.ActiveSignal?.SignalLevel=="INCOMING"&&radar.ActiveSignal?.ReadAt!=null&&radar.Unread==null,"incoming read active");});
  Check("T09 INCOMING to COMPLETED removes warning dot",()=>{using var radar=new ResetRadar(Path.Combine(root,"t09"));var item=Incoming("6000000000000000009");radar.Apply([item],now);radar.Read(item.EventId,item.RevisionId);var completed=item with{Phase="COMPLETED",SignalLevel="COMPLETED",PublishedAt=now.AddMinutes(2),RevisionId="completed-revision",ContentHash="completed-content",Summary="Codex global reset has been applied for all paid plans."};radar.Apply([completed],now.AddMinutes(2));Assert(radar.ActiveSignal==null&&radar.Snapshot().Events.Single().SignalLevel=="COMPLETED","terminal removes active");});
  Check("T10 Weekly 13 warning and read WATCH remain independent",()=>{using var service=new MonitorService(Path.Combine(root,"t10"));var item=Watch("6000000000000000010");service.Radar.Apply([item],now);service.Radar.Read(item.EventId,item.RevisionId);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly="13%"};overlay.Render();Assert(Theme.QuotaColor(13)==Theme.Warning&&overlay.RadarSignalLevel=="WATCH"&&!overlay.RadarSignalUnread&&overlay.RadarDotBounds.X>overlay.ClientSize.Width-20*overlay.UiScale,"13 and watch dot");});
  Check("T11 Weekly 3 critical and read WATCH remain independent",()=>{using var service=new MonitorService(Path.Combine(root,"t11"));var item=Watch("6000000000000000011");service.Radar.Apply([item],now);service.Radar.Read(item.EventId,item.RevisionId);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly="3%"};overlay.Render();Assert(Theme.QuotaColor(3)==Theme.Critical&&overlay.RadarSignalLevel=="WATCH"&&!overlay.RadarSignalUnread,"3 and watch dot");});
  Check("T12 Weekly 3 critical and read INCOMING remain independent",()=>{using var service=new MonitorService(Path.Combine(root,"t12"));var item=Incoming("6000000000000000012");service.Radar.Apply([item],now);service.Radar.Read(item.EventId,item.RevisionId);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly="3%"};overlay.Render();Assert(Theme.QuotaColor(3)==Theme.Critical&&overlay.RadarSignalLevel=="INCOMING"&&!overlay.RadarSignalUnread,"3 and incoming dot");});
  AtomicJson.Save(Path.Combine(root,"active-unread-tests.json"),new{classification="FOCUSED_PRODUCTION_PATH",exe_sha256=ReportExporter.ExeHash(),total=results.Count,failed,results});if(failed>0)Environment.ExitCode=1;
 }
 internal static void CheckCurrent(string output){string root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"CodexUsageMonitor");using var radar=new ResetRadar(root);var active=radar.ActiveSignal;AtomicJson.Save(Path.GetFullPath(output),new{classification="ACTUAL_EXISTING_FIELD_TRIAL_STATE_READ_ONLY",exe_sha256=ReportExporter.ExeHash(),checked_utc=DateTimeOffset.UtcNow,active_signal_present=active!=null,active_signal_level=active?.SignalLevel??"NONE",read_status=active==null?"NO_ACTIVE_SIGNAL":active.ReadAt==null?"UNREAD":"READ",compact_marker=active==null?"NONE":active.ReadAt==null?"FILLED_BADGE_WITH_ATTENTION":"SMALL_ACTIVE_DOT",event_content_disclosed=false,quota_values_disclosed=false,state_mutated=false});}
}
