using System.Runtime.InteropServices;
using System.Text;
namespace CodexUsageMonitor;

internal static class Rc4ActiveUnreadNative {
 [DllImport("user32.dll")] static extern IntPtr GetThreadDesktop(uint id);
 [DllImport("kernel32.dll")] static extern uint GetCurrentThreadId();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern bool GetUserObjectInformation(IntPtr obj,int index,StringBuilder text,uint size,out uint needed);
 [DllImport("user32.dll")] static extern bool PrintWindow(IntPtr window,IntPtr dc,uint flags);
 public static void Attach(OverlayForm main,MonitorService mainService,string[] args){int index=Array.IndexOf(args,"--rc4-active-unread-native");if(index<0)return;string output=Path.GetFullPath(args[index+1]);Directory.CreateDirectory(output);var desktop=new StringBuilder(256);GetUserObjectInformation(GetThreadDesktop(GetCurrentThreadId()),2,desktop,512,out _);if(!desktop.ToString().StartsWith("CUM_RC4_QA_",StringComparison.Ordinal))throw new InvalidOperationException("Active/unread native QA requires the non-input desktop.");
  var checks=new List<object>();var frames=new List<object>();int failures=0;
  void Check(string id,bool value,object? detail=null){if(!value)failures++;checks.Add(new{id,result=value?"PASS":"FAIL",classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",detail});AtomicJson.Save(Path.Combine(output,"checks.json"),checks);}
  main.Shown+=async(_,_)=>{try{main.Hide();
   async Task<Bitmap> Capture(Form form,string name){if(!form.Visible)form.Show();await Task.Delay(240);form.Invalidate(true);form.Refresh();Application.DoEvents();using(var warm=new Bitmap(form.Width,form.Height))using(var g=Graphics.FromImage(warm)){var dc=g.GetHdc();try{PrintWindow(form.Handle,dc,2);}finally{g.ReleaseHdc(dc);}}await Task.Delay(80);var image=new Bitmap(form.Width,form.Height);using(var g=Graphics.FromImage(image)){var dc=g.GetHdc();try{if(!PrintWindow(form.Handle,dc,2))throw new InvalidOperationException("PrintWindow failed");}finally{g.ReleaseHdc(dc);}}string path=Path.Combine(output,name+".png");image.Save(path);frames.Add(new{name,path=Path.GetFileName(path),dpi=form.DeviceDpi,width=form.Width,height=form.Height,desktop=desktop.ToString(),input_desktop_switched=false});return image;}
   int Count(Bitmap image,Rectangle bounds,Color color){bounds.Intersect(new(Point.Empty,image.Size));int count=0;for(int y=bounds.Top;y<bounds.Bottom;y++)for(int x=bounds.Left;x<bounds.Right;x++)if(image.GetPixel(x,y).ToArgb()==color.ToArgb())count++;return count;}
   async Task Compact(string name,string weekly,string level,bool read){L.SetLanguage("en-US");using var service=new MonitorService(Path.Combine(output,"data-"+name));if(level!="NONE"){var item=Rc4SignalPolishTests.Signal(level,"6100000000000000"+(frames.Count+10).ToString());service.Radar.Apply([item],DateTimeOffset.UtcNow);if(read){using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);page.Show();await Task.Delay(240);Application.DoEvents();Check(name+" formal event open marks read and keeps active",service.Radar.Unread==null&&service.Radar.ActiveSignal?.ReadAt!=null&&service.Radar.ActiveSignal?.SignalLevel==level);page.Close();}}service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly=weekly,TestAge="77s",TestCountdownTip=L.T("Overlay.CountdownNormal",77),TestRadarCoverage="67%"};overlay.Render();using var image=await Capture(overlay,name);var badge=overlay.RadarBadgeBounds;var dot=overlay.RadarDotBounds;float k=overlay.UiScale;var number=Rectangle.Round(new RectangleF(22*k,13*k,112*k,46*k));int numberWarning=Count(image,number,Theme.Warning),numberCritical=Count(image,number,Theme.Critical),badgeAmber=Count(image,badge,Theme.Warning),badgeRed=Count(image,badge,Theme.ResetAlert),dotAmber=Count(image,dot,Theme.Warning),dotRed=Count(image,dot,Theme.ResetAlert);bool unread=level!="NONE"&&!read;bool marker=(level switch{"NONE"=>badgeAmber==0&&badgeRed==0,"WATCH" when unread=>badgeAmber>badge.Width*badge.Height*.3,"WATCH"=>dotAmber>dot.Width*dot.Height*.3&&badgeAmber<badge.Width*badge.Height*.3,"INCOMING" when unread=>badgeRed>badge.Width*badge.Height*.3,"INCOMING"=>dotRed>dot.Width*dot.Height*.3&&badgeRed<badge.Width*badge.Height*.3,_=>false})&&overlay.RadarSignalUnread==unread;Check(name+" marker size color and attention",marker,new{badge,dot,badgeAmber,badgeRed,dotAmber,dotRed,overlay.RadarSignalLevel,overlay.RadarSignalUnread});Check(name+" quota color remains independent",weekly=="13%"?numberWarning>8&&numberCritical==0:numberCritical>8&&numberWarning==0,new{numberWarning,numberCritical});Check(name+" fixed Compact geometry",overlay.ClientSize==new Size((int)(156*k),(int)(88*k))&&badge.Right<=overlay.ClientSize.Width&&dot.Right<=overlay.ClientSize.Width,new{overlay.ClientSize,badge,dot});if(level!="NONE"){string expected=(level,read) switch{("WATCH",false)=>"New Reset Watch",("WATCH",true)=>"Reset Watch — already viewed, signal still active",("INCOMING",false)=>"New Reset Incoming",_=>"Reset Incoming — already viewed, still active"};Check(name+" English tooltip semantics",overlay.RadarTooltip==expected,new{actual=overlay.RadarTooltip,expected});}overlay.Close();}
   await Compact("T01-no-event-13","13%","NONE",false);
   await Compact("T02-watch-unread-13","13%","WATCH",false);
   await Compact("T03-watch-read-13","13%","WATCH",true);
   await Compact("T07-incoming-unread-13","13%","INCOMING",false);
   await Compact("T08-incoming-read-13","13%","INCOMING",true);
   await Compact("T11-watch-read-3","3%","WATCH",true);
   await Compact("T12-incoming-read-3","3%","INCOMING",true);
   L.SetLanguage("en-US");{var boundaryNow=DateTimeOffset.UtcNow;string dir=Path.Combine(output,"boundary-watch-49h");var item=Rc4SignalPolishTests.Signal("WATCH","6150000000000000001") with{PublishedAt=boundaryNow.AddHours(-49),FirstSeen=boundaryNow.AddHours(-49),LastSeen=boundaryNow.AddHours(-49),ReadAt=boundaryNow.AddHours(-48)};AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Events=[item]});using var service=new MonitorService(dir);service.Settings.Compact=true;using(var overlay=new OverlayForm(service,true){TestWeekly="13%",TestAge="77s",TestCountdownTip=L.T("Overlay.CountdownNormal",77),TestRadarCoverage="67%"}){overlay.Render();using var image=await Capture(overlay,"T05-watch-read-49h");Check("T05 49h TEAM WATCH keeps small active dot",overlay.RadarSignalLevel=="WATCH"&&!overlay.RadarSignalUnread&&Count(image,overlay.RadarDotBounds,Theme.Warning)>overlay.RadarDotBounds.Width*overlay.RadarDotBounds.Height*.3);}using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);using var pageImage=await Capture(page,"radar-watch-read-49h-en-US");Check("T05 Radar page agrees with 49h active WATCH",page.DisplayedRadarStatus==L.T("Radar.StatusWatch")&&page.DisplayedActiveSignalRows==1&&page.DisplayedSignalStatus==L.T("Radar.SignalStatus",L.T("Radar.SignalActiveWatch"))&&page.DisplayedReadStatus==L.T("Radar.ReadStatus",L.T("Radar.ReadRead")),new{page.DisplayedRadarStatus,page.DisplayedActiveSignalRows,page.DisplayedSignalStatus,page.DisplayedReadStatus});page.Close();}
   foreach(var language in new[]{"en-US","zh-TW"}){L.SetLanguage(language);using var service=new MonitorService(Path.Combine(output,"page-watch-"+language));var item=Rc4SignalPolishTests.Signal("WATCH",language=="en-US"?"6200000000000000001":"6200000000000000002");service.Radar.Apply([item],DateTimeOffset.UtcNow);service.Radar.Read(item.EventId,item.RevisionId);using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);using var image=await Capture(page,"radar-watch-read-"+language);Check("Radar WATCH separates active and read "+language,page.DisplayedSignalStatus==L.T("Radar.SignalStatus",L.T("Radar.SignalActiveWatch"))&&page.DisplayedReadStatus==L.T("Radar.ReadStatus",L.T("Radar.ReadRead")),new{page.DisplayedSignalStatus,page.DisplayedReadStatus});page.Close();}
   foreach(var language in new[]{"en-US","zh-TW"}){L.SetLanguage(language);using var service=new MonitorService(Path.Combine(output,"page-incoming-"+language));var item=Rc4SignalPolishTests.Signal("INCOMING",language=="en-US"?"6200000000000000003":"6200000000000000004");service.Radar.Apply([item],DateTimeOffset.UtcNow);service.Radar.Read(item.EventId,item.RevisionId);using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);using var image=await Capture(page,"radar-incoming-read-"+language);Check("Radar INCOMING separates active and read "+language,page.DisplayedSignalStatus==L.T("Radar.SignalStatus",L.T("Radar.SignalActiveIncoming"))&&page.DisplayedReadStatus==L.T("Radar.ReadStatus",L.T("Radar.ReadRead")),new{page.DisplayedSignalStatus,page.DisplayedReadStatus});page.Close();}
  }catch(Exception ex){failures++;File.WriteAllText(Path.Combine(output,"error.txt"),ex.ToString());}finally{AtomicJson.Save(Path.Combine(output,"complete.json"),new{classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",exe_sha256=ReportExporter.ExeHash(),total=checks.Count,failed=failures,frames,input_desktop_switched=false});Environment.ExitCode=failures==0?0:1;main.Close();Application.Exit();}};
 }
}
