using System.Runtime.InteropServices;
using System.Text;
namespace CodexUsageMonitor;
internal static class Rc4CoverageNative {
 [DllImport("user32.dll")] static extern IntPtr GetThreadDesktop(uint id);
 [DllImport("kernel32.dll")] static extern uint GetCurrentThreadId();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern bool GetUserObjectInformation(IntPtr obj,int index,StringBuilder text,uint size,out uint needed);
 [DllImport("user32.dll")] static extern bool PrintWindow(IntPtr hwnd,IntPtr dc,uint flags);
 internal static void Attach(OverlayForm main,MonitorService mainService,string[] args){int index=Array.IndexOf(args,"--rc4-coverage-native");if(index<0)return;string output=args[index+1];Directory.CreateDirectory(output);var desktop=new StringBuilder(256);GetUserObjectInformation(GetThreadDesktop(GetCurrentThreadId()),2,desktop,512,out _);if(!desktop.ToString().StartsWith("CUM_RC4_QA_"))throw new InvalidOperationException("Private desktop required");
  main.Shown+=async(_,_)=>{var frames=new List<object>();int failed=0;try{
   async Task Capture(Form form,string name){form.Show();await Task.Delay(250);form.Refresh();Application.DoEvents();using var bitmap=new Bitmap(form.Width,form.Height);using(var g=Graphics.FromImage(bitmap)){var dc=g.GetHdc();try{if(!PrintWindow(form.Handle,dc,2))throw new Exception("PrintWindow failed");}finally{g.ReleaseHdc(dc);}if(form is ProductForm product)foreach(var b in product.AllControls().OfType<QuietButton>().Where(x=>x.Visible)){using var im=new Bitmap(b.Width,b.Height);b.DrawToBitmap(im,new(Point.Empty,b.Size));var pt=b.PointToScreen(Point.Empty);g.DrawImageUnscaled(im,pt.X-form.Left,pt.Y-form.Top);}}bitmap.Save(Path.Combine(output,name+".png"));frames.Add(new{name,dpi=form.DeviceDpi,width=form.Width,height=form.Height,desktop=desktop.ToString(),classification="ACTUAL_NATIVE_PRINTWINDOW_NON_INPUT_DESKTOP"});}
   foreach(string lang in new[]{"en-US","zh-TW"})foreach(int count in new[]{-1,4,5,6}){string name=lang+"-"+count;string dir=Path.Combine(output,"data-"+name);var state=Rc4CoverageTests.State(Math.Max(0,count),DateTimeOffset.UtcNow,count<0);AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);using var service=new MonitorService(dir);L.SetLanguage(lang);service.Settings.Compact=true;using(var overlay=new OverlayForm(service,true){TestWeekly="27%",TestAge="8s"}){overlay.Render();await Capture(overlay,name+"-compact");string expected=count<0?"◔--%":count==4?"◔67%":count==5?"◔83%":"◔100%";if(overlay.RadarCoverageText!=expected||overlay.ClientSize!=new Size((int)(156*overlay.UiScale),(int)(88*overlay.UiScale)))throw new Exception("Compact coverage or dimensions");overlay.Close();}if(count is -1 or 4){using var page=new ResetInfoForm(service,null);await Capture(page,name+"-ring");if(!page.AllControls().OfType<RadarCoverageView>().Single().AccessibleName!.Contains(count<0?"--%":"67%"))throw new Exception("Ring semantic mismatch");page.Close();}}
  }catch(Exception ex){failed++;File.WriteAllText(Path.Combine(output,"error.txt"),ex.ToString());}finally{AtomicJson.Save(Path.Combine(output,"complete.json"),new{exe_sha256=ReportExporter.ExeHash(),failed,total=frames.Count,frames,input_desktop_switched=false});Environment.ExitCode=failed>0?1:0;main.Close();Application.Exit();}};
 }
}
