using System.Net;
using System.Text.Json;
namespace CodexUsageMonitor;
internal static class Rc4CoverageTests {
 internal static RadarState State(int readable,DateTimeOffset now,bool pending=false)=>new(){Sources=ResetRadar.Sources.Select((d,i)=>new SourceStatus(d.Id,d.Url,i<readable?"HEALTHY":"DEGRADED",pending&&i==5?null:now,i<readable?now.AddSeconds(-1):null,HttpStatus:i<readable?200:403,Error:i<readable?"":"HTTP_403",SourceClass:d.SourceClass)).ToList()};
 internal static void Run(string root){Directory.CreateDirectory(root);var results=new List<object>();int failed=0;var now=DateTimeOffset.UtcNow;
  void Check(string id,Action test){try{test();results.Add(new{id,result="PASS"});}catch(Exception ex){failed++;results.Add(new{id,result="FAIL",error=ex.ToString()});}}
  void Assert(bool value){if(!value)throw new Exception("Assertion failed");}
  Check("first sweep unknown",()=>{Assert(RadarCoverage.Measure(new(),true,now).coverage_percent==null);Assert(RadarCoverage.Measure(State(5,now,true),true,now).coverage_percent==null);});
  foreach(var pair in new[]{(4,67),(5,83),(6,100),(0,0)})Check($"ratio {pair.Item1}/6",()=>Assert(RadarCoverage.Measure(State(pair.Item1,now),true,now).coverage_percent==pair.Item2));
  Check("official includes status, team and zero community",()=>{var p=RadarCoverage.Measure(State(6,now),true,now);Assert(p.official_total==4&&p.team_total==2&&p.community_total==0);});
  Check("timeout grace and stale expiry",()=>{var state=State(6,now);var d=ResetRadar.Sources[0];state.Sources[0]=state.Sources[0] with{Status="DEGRADED",LastSuccess=now.AddMinutes(-16),LastAttempt=now,HttpStatus=0,Error="TIMEOUT"};Assert(RadarCoverage.Measure(state,true,now).coverage_percent==100);Assert(RadarCoverage.Measure(state,true,now.AddMinutes(18)).coverage_percent<100);});
  foreach(string error in new[]{"HTTP_403","PARSER_ERROR","PARSER_TIMEOUT","RESPONSE_TOO_LARGE"})Check("immediate exclusion "+error,()=>{var state=State(6,now);state.Sources[0]=state.Sources[0] with{Status="DEGRADED",HttpStatus=error=="HTTP_403"?403:200,Error=error};Assert(RadarCoverage.Measure(state,true,now).coverage_percent==83);});
  Check("disabled unknown and zero enabled",()=>{var p=RadarCoverage.Measure(State(6,now),false,now);Assert(p.coverage_percent==null&&p.enabled_sources==0);});
  Check("production sweep persistence and no-op poll",()=>{string dir=Path.Combine(root,"sweep");AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Sources=[new("legacy-unknown","https://openai.com/old")]});using(var radar=new ResetRadar(dir,new Handler())){radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.Snapshot().CoverageTimeline.Single().coverage_percent==100);radar.Poll(false,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.Snapshot().CoverageTimeline.Count==1);}using var reopened=new ResetRadar(dir);Assert(reopened.Snapshot().CoverageTimeline.Single().readable_sources==6);});
  Check("production transient timeout retains sweep coverage",()=>{string dir=Path.Combine(root,"transient");var handler=new Handler();using var radar=new ResetRadar(dir,handler);radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();handler.Fail=true;radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();var state=radar.Snapshot();Assert(state.Sources.Single(x=>x.Id==ResetRadar.Sources[0].Id).Status=="DEGRADED");Assert(state.CoverageTimeline.Count==2&&state.CoverageTimeline.All(x=>x.coverage_percent==100));});
  Check("duplicate legacy source IDs do not break Poll",()=>{string dir=Path.Combine(root,"duplicate");var state=State(6,now);state.Sources.Add(state.Sources[0] with{LastAttempt=now.AddMinutes(-10)});AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);using var radar=new ResetRadar(dir,new Handler());radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.Snapshot().Sources.Count==6&&radar.Snapshot().CoverageTimeline.Single().coverage_percent==100);});
  Check("Poll signal includes producing source success",()=>{string dir=Path.Combine(root,"producing");var state=State(5,now);state.Sources=state.Sources.Select(x=>x with{NextCheck=now.AddHours(1)}).ToList();state.Sources[5]=state.Sources[5] with{LastAttempt=null,NextCheck=null};AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);using var radar=new ResetRadar(dir,new Handler{Signal=true});radar.Poll(false,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.Snapshot().SignalHistory.Single().CoverageAtObservation?.coverage_percent==100);Assert(radar.Snapshot().CoverageTimeline.Single().coverage_percent==100);});
  Check("WATCH INCOMING and captured coverage",()=>{string dir=Path.Combine(root,"signals");AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),State(4,now));using var radar=new ResetRadar(dir);foreach(var pair in new[]{("WATCH","When I say excellent service for existing Codex users, that includes the occasional reset."),("INCOMING","Codex global reset will be applied tomorrow around 6 PM PT for all paid plans.")}){string html="<ul><li class=\"feed-item\"><p class=\"feed-text\">"+pair.Item2+"</p><a href=\"https://x.com/thsottiaux/status/4000000000000000001\">original</a><a class=\"feed-time\">1h ago</a></li></ul>";var parsed=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),html,now,out _);Assert(parsed.Single().SignalLevel==pair.Item1);radar.Apply(parsed,now);Assert(radar.Unread?.SignalLevel==pair.Item1);Assert(radar.Snapshot().SignalHistory.Last().CoverageAtObservation?.coverage_percent==67);}});
  Check("bilingual coverage Log and integrity",()=>{string dir=Path.Combine(root,"log");var state=State(4,now);state.CoverageTimeline=[RadarCoverage.Measure(State(6,now.AddMinutes(-5)),true,now.AddMinutes(-5)),RadarCoverage.Measure(state,true,now)];AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);using var service=new MonitorService(dir);foreach(string lang in new[]{"en-US","zh-TW"}){string path=ReportExporter.Export(service,new(now.AddDays(-3),now.AddMinutes(1)),false,CancellationToken.None,Path.Combine(root,"coverage-"+lang+".log"),lang);var text=File.ReadAllText(path);Assert(text.Contains("RADAR_COVERAGE_TIMELINE")&&text.Contains("RADAR_SOURCE_BREAKDOWN")&&text.Contains("\"minimum_coverage_percent\":67")&&text.Contains("\"average_coverage_percent\":83.5"));PublicReportTests.VerifyIntegrity(path);}});
  Check("bilingual accessible ring summary",()=>{foreach(string lang in new[]{"en-US","zh-TW"}){L.SetLanguage(lang);using var view=new RadarCoverageView();view.UpdateCoverage(RadarCoverage.Measure(State(4,now),true,now));Assert(view.Summary.Contains("67% · ")&&!view.Summary.Contains("繚")&&!view.Summary.Contains("Radar.Coverage"));}});
  Check("quota core smoke",()=>{var rows=R004Tests.Rows(100,99);var result=DailyUsageCalculator.Calculate(rows,TimeZoneInfo.Local,rows[0].observed_at_utc.AddMinutes(-1),rows[1].observed_at_utc.AddMinutes(1));Assert(result.Days.Sum(x=>x.observed_drawdown_pp??0)==1);});
  AtomicJson.Save(Path.Combine(root,"coverage-tests.json"),new{classification="SYNTHETIC_PRODUCTION_PATH",exe_sha256=ReportExporter.ExeHash(),total=results.Count,failed,results});if(failed>0)Environment.ExitCode=1;
 }
 sealed class Handler:HttpMessageHandler {internal bool Fail,Signal;protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){if(Fail&&request.RequestUri!.AbsoluteUri==ResetRadar.Sources[0].Url)throw new OperationCanceledException("Synthetic timeout");return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(Signal&&request.RequestUri!.DnsSafeHost=="codex-reset.com"?"<ul><li class=\"feed-item\"><p class=\"feed-text\">Codex global reset will be applied tomorrow around 6 PM PT for all paid plans.</p><a href=\"https://x.com/thsottiaux/status/4000000000000000002\">original</a><a class=\"feed-time\">1h ago</a></li></ul>":Rc4FieldTrialTests.HealthyPayload(request))});}}
}


