using System.Net;
using System.Text;
using System.Text.Json;

namespace CodexUsageMonitor;

// Headless, isolated rc.4 tests. They exercise shipped parsers and state transitions,
// never fetch X, never start a Codex producer, and never show a desktop window.
internal static class Rc4FieldTrialTests
{
 static readonly DateTimeOffset Now=DateTimeOffset.Parse("2026-09-11T12:00:00Z");
 public static void Run(string[] args)
 {
  int pos=Array.IndexOf(args,"--test-root");string root=Path.GetFullPath(args[pos+1]);Directory.CreateDirectory(root);
  var results=new List<object>();int failed=0;
  void Assert(bool value,string message="assertion"){if(!value)throw new InvalidOperationException(message);}
  void Check(string id,Action action){try{action();results.Add(new{id,result="PASS",classification="SYNTHETIC_PRODUCTION_PATH"});}catch(Exception e){failed++;results.Add(new{id,result="FAIL",classification="SYNTHETIC_PRODUCTION_PATH",error=e.GetType().Name+": "+e.Message});}}
  Announcement One(string source,string payload){var definition=ResetRadar.Sources.Single(x=>x.Id==source);var values=Rc4Radar.Parse(definition,payload,Now,out _);Assert(values.Count==1,source+" expected one event, got "+values.Count);return values.Single();}
  Announcement Watch(string id)=>One("team-codex-reset",TeamHtml(id,"When I say excellent service for existing Codex users, that includes the occasional reset."));
  Announcement Incoming(string id)=>One("team-codex-reset",TeamHtml(id,"Codex global reset will be applied tomorrow around 6 PM PT for all paid plans."));

  Check("T01 rc.3 quota core smoke",()=>{var rows=R004Tests.Rows(100,99);var calc=DailyUsageCalculator.Calculate(rows,TimeZoneInfo.Local,rows[0].observed_at_utc.AddMinutes(-1),rows[1].observed_at_utc.AddMinutes(1));Assert(calc.Days.Sum(x=>x.observed_drawdown_pp??0)==1);});
  Check("T02 no signal no alert",()=>{using var radar=new ResetRadar(Path.Combine(root,"t02"));Assert(radar.Unread==null&&radar.AlertLevel=="NONE");});
  Check("T03 team vague hint WATCH",()=>{var a=Watch("2000000000000000003");Assert(a.SignalLevel=="WATCH"&&a.ResetUtc==null);using var radar=new ResetRadar(Path.Combine(root,"t03"));radar.Apply([a],Now);Assert(radar.AlertLevel=="WATCH");});
  Check("T04 explicit team reset tomorrow INCOMING",()=>{var a=Incoming("2000000000000000004");Assert(a.SignalLevel=="INCOMING"&&a.Phase=="PLANNED"&&a.Effect=="AUTOMATIC_QUOTA_RESET"&&a.ResetUtc>Now);});
  Check("T05 official OpenAI reset incoming",()=>{var a=One("openai-release-notes-rss",OfficialHtml("official-incoming","Codex global reset for all paid plans will begin tomorrow around 6 PM PT."));Assert(a.SourceClass=="OFFICIAL_OPENAI"&&a.SignalLevel=="INCOMING"&&a.Phase=="PLANNED");});
  Check("T06 banked credit is separate",()=>{var a=One("openai-release-notes-rss",OfficialHtml("credit","One Codex banked reset credit for paid plans will be provided tomorrow around 6 PM PT."));Assert(a.Effect=="BANKED_CREDIT_GRANT"&&a.SignalLevel=="NONE"&&a.Phase=="PLANNED");});
  Check("T07 forecast only has no alert",()=>{var values=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),TeamHtml("2000000000000000007","An 87% forecast says a Codex reset might happen."),Now,out _);Assert(values.Count==0);});
  Check("T08 unrelated news has no alert",()=>{var values=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),TeamHtml("2000000000000000008","Codex Spark retirement details are available."),Now,out _);Assert(values.Count==0);});
  Check("T09 same original through two relays deduplicates",()=>{string id="2000000000000000009";var a=Watch(id);var b=One("team-modelyard-rss",TeamFeed(id,"When I say excellent service for existing Codex users, that includes the occasional reset."));using var radar=new ResetRadar(Path.Combine(root,"t09"));radar.Apply([a,b],Now);var item=radar.Snapshot().Events.Single();Assert(item.CanonicalOriginalId=="x:"+id&&(item.EvidenceSources?.Select(x=>x.SourceId).Distinct().Count()??0)>=3);});
  Check("T10 minor relay edit does not re-alert",()=>{string id="2000000000000000010";using var radar=new ResetRadar(Path.Combine(root,"t10"));var first=Watch(id);radar.Apply([first],Now);radar.Read(first.EventId);var stamp=radar.Snapshot().Events.Single().ReadAt;var minor=One("team-modelyard-rss",TeamFeed(id,"When I say excellent service for existing Codex users, that includes the occasional reset for existing accounts."));radar.Apply([minor],Now.AddMinutes(1));Assert(radar.Unread==null&&radar.Snapshot().Events.Single().ReadAt==stamp);});
  Check("T11 explicit time is major unread revision",()=>{string id="2000000000000000011";using var radar=new ResetRadar(Path.Combine(root,"t11"));var first=Watch(id);radar.Apply([first],Now);radar.Read(first.EventId);var incoming=One("team-modelyard-rss",TeamFeed(id,"Codex global reset will be applied tomorrow around 6 PM PT for all paid plans."));radar.Apply([incoming],Now.AddMinutes(1));var state=radar.Snapshot();Assert(radar.Unread?.SignalLevel=="INCOMING"&&state.Transitions.Any(x=>x.FromSignal=="WATCH"&&x.ToSignal=="INCOMING"));Assert(state.SignalHistory.Count==2&&state.SignalHistory[0].SignalLevel=="WATCH"&&state.SignalHistory[1].SignalLevel=="INCOMING"&&state.SignalHistory[0].Timestamp==Now&&state.SignalHistory[1].Timestamp==Now.AddMinutes(1)&&state.SignalHistory[0].PublishedAt!=null&&state.SignalHistory[0].ReadAt!=null&&state.SignalHistory[1].ReadAt==null&&state.SignalHistory.Select(x=>x.ContentHash).Distinct().Count()==2);});
  Check("T12 original URL is preferred",()=>{var a=Incoming("2000000000000000012");Assert(Rc4Radar.PreferredUrl(a)=="https://x.com/thsottiaux/status/2000000000000000012"&&a.RelayUrl=="https://codex-reset.com/tibo");});
  Check("T13 relay event is labeled",()=>{var a=Watch("2000000000000000013");Assert(Rc4Radar.SourceLabel(a,"en-US").Contains("community relay")&&Rc4Radar.SourceLabel(a,"zh-TW").Contains("社群轉送"));});
  Check("T14 Status reset is supporting context",()=>{var a=One("openai-status-rss",Feed("status-reset","Investigating unexpected usage limit resets affecting Codex."));Assert(a.SignalLevel=="SUPPORTING_CONTEXT"&&!Rc4Radar.IsAlert(a));});
  Check("T15 Help 403 is isolated",()=>{using var radar=new ResetRadar(Path.Combine(root,"t15"),new SourceHandler(request=>request.RequestUri!.DnsSafeHost=="help.openai.com"?new(HttpStatusCode.Forbidden):Healthy(request)));radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();var state=radar.Snapshot();Assert(state.Sources.Count==ResetRadar.Sources.Length&&state.Sources.Count(x=>x.Status=="DEGRADED")==1&&state.Sources.Count(x=>x.Status=="HEALTHY")==ResetRadar.Sources.Length-1);});
  Check("T16 one relay 403 is isolated",()=>{using var radar=new ResetRadar(Path.Combine(root,"t16"),new SourceHandler(request=>request.RequestUri!.DnsSafeHost=="codex-reset.com"?new(HttpStatusCode.Forbidden):Healthy(request)));radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.Snapshot().Sources.Single(x=>x.Id=="team-codex-reset").Status=="DEGRADED"&&radar.Snapshot().Sources.Where(x=>x.Id!="team-codex-reset").All(x=>x.Status=="HEALTHY"));});
  Check("T17 all Radar offline leaves quota core intact",()=>{using var service=new MonitorService(Path.Combine(root,"t17-service"));var snapshot=new Snapshot(Now,Now,0,"SYNTHETIC","STABLE_SCOPE","SYNTHETIC","0.153.4",[new("codex","Codex","primary",10080,50,Now.AddDays(7).ToUnixTimeSeconds(),"VALID","pro",null,null,null,"")],2,[]);service.MainClock.Observe(snapshot,service.Monotonic);using var radar=new ResetRadar(Path.Combine(root,"t17-radar"),new SourceHandler(_=>throw new HttpRequestException("synthetic offline")));radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();Assert(radar.FailedSourceCount==ResetRadar.Sources.Length&&service.MainClock.Value?.Remaining==50&&!service.MainClock.Failed);});
  Check("T18 source health UI semantics",()=>{var uiNow=DateTimeOffset.UtcNow;string dir=Path.Combine(root,"t18");AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Sources=ResetRadar.Sources.Select(x=>new SourceStatus(x.Id,x.Url,"HEALTHY",uiNow,uiNow,uiNow.AddMinutes(15),HttpStatus:200,SourceClass:x.SourceClass,DisplayName:x.DisplayName,Adapter:x.Adapter)).ToList()});using var service=new MonitorService(dir);using var page=new ResetInfoForm(service,null);string text=string.Join("\n",page.AllControls().Select(x=>x.Text));Assert(page.AllControls().OfType<RadarCoverageView>().Single().Summary.Contains("6 / 6")&&text.Contains(L.T("Radar.SourcesHeading"))&&page.AllControls().OfType<Button>().Any(x=>x.Text==L.T("Radar.CheckNow")));});
  Check("T19 English and zh-TW card",()=>{string original=L.Language;try{foreach(var language in new[]{"en-US","zh-TW"}){L.SetLanguage(language);using var service=new MonitorService(Path.Combine(root,"t19-"+language));var a=Incoming("2000000000000000019");service.Radar.Apply([a],Now);using var page=new ResetInfoForm(service,service.Radar.Unread);string text=string.Join("\n",page.AllControls().Select(x=>x.Text));Assert(text.Contains(L.T("Radar.BadgeIncoming"))&&text.Contains(L.T("Radar.OpenOriginal"))&&!text.Contains("Radar."));}}finally{L.SetLanguage(original);}});
  Check("T20 WATCH and INCOMING colors",()=>{using var watchService=new MonitorService(Path.Combine(root,"t20-watch"));var watch=Watch("2000000000000000020");watchService.Radar.Apply([watch],Now);using var watchPage=new ResetInfoForm(watchService,watchService.Radar.Unread);Assert(watchPage.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.Warning);using var incomingService=new MonitorService(Path.Combine(root,"t20-incoming"));var incoming=Incoming("2000000000000000021");incomingService.Radar.Apply([incoming],Now);using var incomingPage=new ResetInfoForm(incomingService,incomingService.Radar.Unread);Assert(incomingPage.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.ResetAlert);});
  Check("T21 Compact geometry unchanged",()=>{using var service=new MonitorService(Path.Combine(root,"t21"));using var overlay=new OverlayForm(service,true);service.Settings.Compact=true;overlay.TestScale=1;overlay.Render();Assert(overlay.ClientSize==new Size(156,88)&&overlay.ModeHit==new Rectangle(0,62,24,24)&&overlay.RadarHit==new Rectangle(132,0,24,24));});
  Check("T22 Standard geometry unchanged",()=>{using var service=new MonitorService(Path.Combine(root,"t22"));using var overlay=new OverlayForm(service,true);service.Settings.Compact=false;overlay.TestScale=1;overlay.Render();Assert(overlay.ClientSize==new Size(330,84)&&overlay.ModeHit==new Rectangle(306,56,24,24)&&overlay.RadarHit==new Rectangle(306,0,24,24));});
  Check("T23 Log evidence sections",()=>{string dir=Path.Combine(root,"t23");AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{SourceChecks=[new(Now,"source-check","OFFICIAL_OPENAI","DEGRADED",3,403,"body-hash",Now.AddMinutes(-5),Now.AddMinutes(15),"HTTP_403")]});using var service=new MonitorService(dir);var a=Incoming("2000000000000000023");service.Radar.Apply([a],Now);string file=ReportExporter.Export(service,new(Now.AddDays(-1),Now.AddDays(1)),false,CancellationToken.None,Path.Combine(dir,"field-trial.log"),"en-US");string text=File.ReadAllText(file);foreach(var name in new[]{"RADAR_SOURCE_HEALTH","RADAR_SIGNALS","RADAR_TRANSITIONS","RESET_FIELD_TRIAL_TIMELINE","LOCAL_QUOTA_AROUND_SIGNAL","CORRELATION","EVIDENCE_LIMITATIONS"})Assert(text.Contains("\"section\":\""+name+"\""),name);Assert(text.Contains("what remains unknown",StringComparison.OrdinalIgnoreCase)&&text.Contains("\"candidate_count\":3")&&text.Contains("\"http_status\":403")&&text.Contains("\"body_hash\":\"body-hash\"")&&text.Contains("\"last_success\"")&&text.Contains("\"next_check\""));});
  Check("T24 exported evidence privacy",()=>{string dir=Path.Combine(root,"t24");using var service=new MonitorService(dir);var a=Incoming("2000000000000000024") with{OriginalQuote="contact person@example.com token=secret-value",OriginalSourceUrl="https://x.com/thsottiaux/status/2000000000000000024?token=secret-value",RelayUrl="https://codex-reset.com/tibo?person=user@example.com"};service.Radar.Apply([a],Now);string file=ReportExporter.Export(service,new(Now.AddDays(-1),Now.AddDays(1)),false,CancellationToken.None,Path.Combine(dir,"privacy.log"),"en-US");string text=File.ReadAllText(file);Assert(!text.Contains("person@example.com")&&!text.Contains("secret-value")&&!text.Contains("user@example.com"));});
  Check("T25 no X background source",()=>{Assert(ResetRadar.Sources.All(x=>!new Uri(x.Url).DnsSafeHost.EndsWith("x.com",StringComparison.OrdinalIgnoreCase)));});
  Check("T26 requests have no credentials or browser automation",()=>{var seen=new List<string>();using var radar=new ResetRadar(Path.Combine(root,"t26"),new SourceHandler(request=>{Assert(request.Headers.Authorization==null&&!request.Headers.Contains("Cookie"));Assert(request.RequestUri!.DnsSafeHost is not ("x.com" or "www.x.com"));seen.Add(request.RequestUri.AbsoluteUri);return Healthy(request);}));radar.Poll(true,CancellationToken.None).GetAwaiter().GetResult();Assert(seen.Count==ResetRadar.Sources.Length);});
  Check("T27 all forecast wording is excluded",()=>{foreach(var quote in new[]{"An 87% chance says Codex reset will land tomorrow.","A forecast says a possible Codex reset may happen."}){var values=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),TeamHtml("2000000000000000027",quote),Now,out _);Assert(values.Count==0,quote);}});
  Check("T28 official documentation is not INCOMING",()=>{var values=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="openai-release-notes-rss"),OfficialHtml("documentation","Codex global reset documentation is available today."),Now,out _);Assert(values.Count==1&&values.Single().SignalLevel=="NONE");});
  Check("T29 coverage uses all current configured health",()=>{var degraded=ResetRadar.Sources.Select(x=>new SourceStatus(x.Id,x.Url,"DEGRADED",Now,Now.AddMinutes(-1),Now.AddMinutes(15),1,403,SourceClass:x.SourceClass,DisplayName:x.DisplayName,Adapter:x.Adapter)).ToList();var state=new RadarState{Sources=degraded};Assert(Rc4Radar.Coverage(state,true,Now)=="OFF");state.Sources[0]=state.Sources[0] with{Status="HEALTHY",Failures=0,HttpStatus=200,LastSuccess=Now};Assert(Rc4Radar.Coverage(state,true,Now)=="LIMITED");state.Sources=[state.Sources[0]];Assert(Rc4Radar.Coverage(state,true,Now)!="GOOD");});
  Check("T30 stale relay cannot downgrade or re-alert",()=>{string id="2000000000000000030";using var radar=new ResetRadar(Path.Combine(root,"t30"));var watch=Watch(id);radar.Apply([watch],Now);radar.Read(watch.EventId);var incoming=One("team-modelyard-rss",TeamFeed(id,"Codex global reset will be applied tomorrow around 6 PM PT for all paid plans."));radar.Apply([incoming],Now.AddMinutes(1));radar.Read(radar.Snapshot().Events.Single().EventId);var read=radar.Snapshot().Events.Single().ReadAt;radar.Apply([watch],Now.AddMinutes(2));radar.Apply([incoming],Now.AddMinutes(3));radar.Apply([watch],Now.AddMinutes(4));var state=radar.Snapshot();Assert(state.Events.Single().SignalLevel=="INCOMING"&&state.Events.Single().ResetUtc!=null&&state.Events.Single().ReadAt==read&&radar.Unread==null&&state.Transitions.Count==1&&state.SignalHistory.Count==2);});
  Check("T31 96h evidence survives and unknown banked stays null",()=>{string dir=Path.Combine(root,"t31");using var service=new MonitorService(dir);List<UsageSample> Pair(DateTimeOffset at,string prefix,decimal before,decimal after){var seed=R004Tests.Rows(before,after);var reset=at.AddDays(7);return [seed[0] with{sample_id=prefix+"-a",poll_id=prefix+"-a",observed_at_utc=at,observed_at_local=at,reset_at_utc=reset,reset_at_unix_seconds=reset.ToUnixTimeSeconds(),reset_credits_available_count=null},seed[1] with{sample_id=prefix+"-b",poll_id=prefix+"-b",observed_at_utc=at.AddMinutes(1),observed_at_local=at.AddMinutes(1),reset_at_utc=reset,reset_at_unix_seconds=reset.ToUnixTimeSeconds(),reset_credits_available_count=null}];}service.Radar.Correlate(Pair(Now.AddHours(-80),"old",70,100));service.Radar.Correlate(Pair(Now.AddHours(-1),"new",60,100));Assert(service.Radar.Snapshot().QuotaEvidence.Count==2);string file=ReportExporter.Export(service,new(Now.AddDays(-4),Now.AddDays(1)),false,CancellationToken.None,Path.Combine(dir,"nullable.log"),"en-US");string text=File.ReadAllText(file);Assert(text.Contains("\"BankedBefore\":null")&&text.Contains("\"BankedAfter\":null")&&!text.Contains("\"BankedBefore\":-1"));});
  Check("T32 credit-only movement is evidence not automatic refill",()=>{using var radar=new ResetRadar(Path.Combine(root,"t32"));var rows=R004Tests.Rows(50,50);rows=[rows[0] with{sample_id="credit-a",reset_credits_available_count=2},rows[1] with{sample_id="credit-b",reset_credits_available_count=3}];radar.Correlate(rows);var state=radar.Snapshot();Assert(state.Correlations.Single().Classification=="BANKED_CREDIT_MOVEMENT"&&state.Correlations.Single().Correlation!="PROBABLE"&&state.Correlations.Single().Cause=="UNKNOWN"&&state.QuotaEvidence.Single().BankedBefore==2&&state.QuotaEvidence.Single().BankedAfter==3);});
  Check("T33 Release Notes uses verified HTML fallback",()=>{var source=ResetRadar.Sources.Single(x=>x.Id=="openai-release-notes-rss");Assert(source.Url=="https://openai.com/products/release-notes/"&&source.Adapter=="LEGACY_HTML");var a=One(source.Id,OfficialHtml("fallback","Codex global reset for all paid plans will begin tomorrow around 6 PM PT."));Assert(a.SignalLevel=="INCOMING");});
  Check("T34 terminal states reject stale incoming relays",()=>{foreach(string terminal in new[]{"COMPLETED","CANCELLED"}){string id=terminal=="COMPLETED"?"2000000000000000034":"2000000000000000035";using var radar=new ResetRadar(Path.Combine(root,"t34-"+terminal));var incoming=Incoming(id);var final=incoming with{Phase=terminal,SignalLevel=terminal=="COMPLETED"?"COMPLETED":"NOTICE",ContentHash="terminal-"+terminal,RevisionId="terminal-revision-"+terminal,Source="team-modelyard-rss"};radar.Apply([final],Now);radar.Read(radar.Snapshot().Events.Single().EventId);radar.Apply([incoming],Now.AddMinutes(1));var state=radar.Snapshot();Assert(state.Events.Single().Phase==terminal&&state.Events.Single().SignalLevel==final.SignalLevel&&state.Events.Single().ReadAt!=null&&radar.Unread==null&&state.SignalHistory.Count==1);}});
  Check("T35 partial signal history export keeps every current revision",()=>{string dir=Path.Combine(root,"t35");var a=Watch("2000000000000000036");var b=Incoming("2000000000000000037");var h=new RadarSignalEvidence(Now,a.EventId,a.RevisionId,a.SignalLevel,a.Phase,a.Effect,a.Scope,a.ResetUtc,a.TimeQuality,a.PublishedAt,Now,a.Source,a.SourceClass,a.OriginalSourceUrl,a.RelayUrl,a.OriginalQuote,a.ContentHash,a.SignalReason);AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Events=[a,b],SignalHistory=[h]});using var service=new MonitorService(dir);string file=ReportExporter.Export(service,new(Now.AddDays(-1),Now.AddDays(1)),false,CancellationToken.None,Path.Combine(dir,"signals.log"),"en-US");string text=File.ReadAllText(file);Assert(text.Contains(a.ContentHash)&&text.Contains(b.ContentHash)&&text.Contains("\"PublishedAt\"")&&text.Contains("\"ReadAt\""));});
  Check("T36 nullable or unstable banked values stay inconclusive",()=>{foreach(var unstable in new[]{false,true}){using var radar=new ResetRadar(Path.Combine(root,"t36-"+unstable));var rows=R004Tests.Rows(50,50);rows=[rows[0] with{sample_id="nullable-a-"+unstable,reset_credits_available_count=null},rows[1] with{sample_id="nullable-b-"+unstable,reset_credits_available_count=2,context_assurance=unstable?"SCOPE_NOT_FULLY_VERIFIED":"STABLE_SCOPE"}];radar.Correlate(rows);var state=radar.Snapshot();Assert(state.Correlations.Single().Classification=="INCONCLUSIVE"&&state.Correlations.Single().LocalObservation=="NOT_COMPARABLE"&&state.QuotaEvidence.Single().ScopeAssurance=="SCOPE_NOT_FULLY_VERIFIED");}});
  Check("T37 reset documentation clock and unrelated future verb do not alert",()=>{string body="Codex global reset documentation is available today at 6 PM PT. We will apply a UI fix.";var official=One("openai-release-notes-rss",OfficialHtml("clock-docs",body));Assert(official.ResetUtc!=null&&official.SignalLevel=="NONE");var team=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),TeamHtml("2000000000000000038",body),Now,out _);Assert(team.Count==0);});
  Check("T38 obsolete healthy rows cannot mask a missing configured source",()=>{var configured=ResetRadar.Sources.Take(5).Select(x=>new SourceStatus(x.Id,x.Url,"HEALTHY",Now,Now,Now.AddMinutes(15),HttpStatus:200,SourceClass:x.SourceClass,DisplayName:x.DisplayName,Adapter:x.Adapter)).ToList();configured.Add(new("obsolete-source","https://openai.com/old","HEALTHY",Now,Now,Now.AddMinutes(15),HttpStatus:200,SourceClass:"OFFICIAL_OPENAI"));var state=new RadarState{Sources=configured};Assert(Rc4Radar.HealthyConfiguredCount(state,Now)==5&&Rc4Radar.Coverage(state,true,Now)!="GOOD");});
  Check("T39 countdown uses next schedule and retry state",()=>{string original=L.Language;try{foreach(var language in new[]{"en-US","zh-TW"}){L.SetLanguage(language);var normal=OverlayForm.Countdown(Now,true,false,false,0,Now.AddSeconds(8),"");Assert(normal.text=="8s"&&normal.seconds==8&&normal.tip==L.T("Overlay.CountdownNormal",8));var due=OverlayForm.Countdown(Now,true,true,false,0,Now.AddSeconds(90),"");Assert(due.text=="0s"&&due.state=="REFRESHING");var retry=OverlayForm.Countdown(Now,true,false,false,1,Now.AddSeconds(30),"NETWORK_ERROR");Assert(retry.text=="30s ⚠"&&retry.tip==L.T("Overlay.CountdownRetry",30));Assert(OverlayForm.Countdown(Now,false,false,false,0,null,"").text=="--"&&OverlayForm.Countdown(Now,true,false,true,0,null,"").state=="PAUSED"&&OverlayForm.Countdown(Now,true,false,false,1,Now.AddSeconds(30),"CODEX_NOT_FOUND").state=="OFF");}}finally{L.SetLanguage(original);}});
  Check("T40 Compact countdown and coverage keep 156 by 88",()=>{using var service=new MonitorService(Path.Combine(root,"t40"));using var overlay=new OverlayForm(service,true){TestWeekly="27%",TestAge="8s",TestCountdownTip=L.T("Overlay.CountdownNormal",8),TestRadarCoverage="70%",TestScale=1};service.Settings.Compact=true;overlay.Render();Assert(overlay.ClientSize==new Size(156,88)&&overlay.DisplayText.StartsWith("27%\n8s · ◔70%")&&overlay.CountdownHit.Width>0&&overlay.RadarHit.Y==0);});
  Check("T41 direct legacy EventId preserves terminal phase",()=>{string dir=Path.Combine(root,"t41");string id="2000000000000000041";var stale=Incoming(id);var terminal=stale with{Phase="COMPLETED",SignalLevel="COMPLETED",CanonicalOriginalId="",OriginalId="",IdentityConfidence="LOW_STRUCTURED_FALLBACK",ContentHash="legacy-terminal",RevisionId="legacy-terminal-revision",ReadAt=Now};AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Events=[terminal]});using var radar=new ResetRadar(dir);radar.Apply([stale],Now.AddMinutes(1));var saved=radar.Snapshot().Events.Single();Assert(saved.EventId==stale.EventId&&saved.Phase=="COMPLETED"&&saved.SignalLevel=="COMPLETED"&&saved.ReadAt==Now&&radar.Unread==null);});
  Check("T42 matching announcement cannot promote unknown banked baseline",()=>{using var radar=new ResetRadar(Path.Combine(root,"t42"));var rows=R004Tests.Rows(50,80);var at=rows[1].observed_at_utc;var future=at.AddDays(7);rows=[rows[0] with{sample_id="unknown-banked-a",reset_at_utc=future,reset_at_unix_seconds=future.ToUnixTimeSeconds(),reset_credits_available_count=null},rows[1] with{sample_id="unknown-banked-b",reset_at_utc=future,reset_at_unix_seconds=future.ToUnixTimeSeconds(),reset_credits_available_count=2}];var announcement=Incoming("2000000000000000042") with{ResetUtc=at,Scope="PAID",Eligibility="AS_ANNOUNCED"};radar.Apply([announcement],at.AddMinutes(-1));radar.Correlate(rows);var result=radar.Snapshot().Correlations.Single();Assert(result.Classification=="INCONCLUSIVE"&&result.LocalObservation=="NOT_COMPARABLE"&&result.Correlation!="PROBABLE"&&result.Cause=="UNKNOWN");});
  Check("T43 team clock plus reset documentation is not an action",()=>{string body="At 6 PM PT, Codex reset documentation will be available.";var values=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),TeamHtml("2000000000000000043",body),Now,out _);Assert(values.Count==0);});
  Check("T44 latest configured source controls UI and export health",()=>{var uiNow=DateTimeOffset.UtcNow;string dir=Path.Combine(root,"t44");var rows=ResetRadar.Sources.Select(x=>new SourceStatus(x.Id,x.Url,"HEALTHY",uiNow.AddMinutes(-10),uiNow.AddMinutes(-10),uiNow.AddMinutes(5),HttpStatus:200,SourceClass:x.SourceClass,DisplayName:x.DisplayName,Adapter:x.Adapter)).ToList();var target=ResetRadar.Sources[0];rows.Add(new(target.Id,target.Url,"DEGRADED",uiNow,uiNow.AddHours(-5),uiNow.AddMinutes(15),Failures:2,HttpStatus:503,Error:"HTTP_503",SourceClass:target.SourceClass,DisplayName:target.DisplayName,Adapter:target.Adapter));rows.Add(new("obsolete-source","https://openai.com/old","HEALTHY",uiNow,uiNow,uiNow.AddMinutes(15),HttpStatus:200,SourceClass:"OFFICIAL_OPENAI"));AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),new RadarState{Sources=rows});using var service=new MonitorService(dir);var state=service.Radar.Snapshot();Assert(Rc4Radar.LatestConfiguredSources(state).Count()==ResetRadar.Sources.Length&&Rc4Radar.HealthyConfiguredCount(state,uiNow)==ResetRadar.Sources.Length-1&&service.Radar.FailedSourceCount==1);using var page=new ResetInfoForm(service,null);string ui=string.Join("\n",page.AllControls().Select(x=>x.Text));Assert(page.AllControls().OfType<RadarCoverageView>().Single().Summary.Contains("5 / 6"));string file=ReportExporter.Export(service,new(Now.AddDays(-1),Now.AddDays(1)),false,CancellationToken.None,Path.Combine(dir,"health.log"),"en-US");string text=File.ReadAllText(file);Assert(text.Contains("\"healthy_sources\":5")&&text.Contains("\"failed_sources\":1")&&!text.Contains("obsolete-source"));});
  Check("T45 production scheduler distinguishes success and retry",()=>{var success=MonitorService.NextPollSchedule(Now,0,90);var retry=MonitorService.NextPollSchedule(Now,2,90);Assert(success.seconds==90&&success.next==Now.AddSeconds(90));Assert(retry.seconds==MonitorService.Backoff(2)&&retry.seconds==180&&retry.next==Now.AddSeconds(180));var normal=OverlayForm.Countdown(Now,true,false,false,0,success.next,"");var failedState=OverlayForm.Countdown(Now,true,false,false,2,retry.next,"NETWORK_ERROR");Assert(normal.text=="90s"&&normal.state=="SCHEDULED"&&failedState.text=="180s ⚠"&&failedState.state=="RETRY");});

  AtomicJson.Save(Path.Combine(root,"rc4-field-trial-tests.json"),new{classification="SYNTHETIC_PRODUCTION_PATH",executed_utc=DateTimeOffset.UtcNow,exe_sha256=ReportExporter.ExeHash(),total=results.Count,failed,results});
  if(failed>0)Environment.ExitCode=1;
 }

 static string TeamHtml(string id,string quote)=>"<ul><li class=\"feed-item\"><p class=\"feed-text\">"+WebUtility.HtmlEncode(quote)+"</p><a href=\"https://x.com/thsottiaux/status/"+id+"\">original</a><a class=\"feed-time\">1h ago</a></li></ul>";
 static string TeamFeed(string id,string quote)=>"<?xml version=\"1.0\"?><rss><channel><item><title>Codex team signal</title><guid>relay-"+id+"</guid><link>https://tibo.modelyard.dev/posts/"+id+"</link><description><![CDATA[Source text: "+quote+" https://x.com/thsottiaux/status/"+id+"]]></description><pubDate>Fri, 11 Sep 2026 11:00:00 GMT</pubDate></item></channel></rss>";
  static string Feed(string id,string body)=>"<?xml version=\"1.0\"?><rss><channel><item><title>Codex update</title><guid>"+id+"</guid><link>https://openai.com/index/"+id+"</link><description><![CDATA["+body+"]]></description><pubDate>Fri, 11 Sep 2026 11:00:00 GMT</pubDate></item></channel></rss>";
  static string OfficialHtml(string id,string body)=>"<article id=\""+id+"\"><header><h2><a href=\"/products/release-notes/#"+id+"\">Codex update</a></h2><time datetime=\"2026-09-11T11:00:00Z\">September 11, 2026</time></header><p>"+WebUtility.HtmlEncode(body)+"</p></article>";
  internal static string HealthyPayload(HttpRequestMessage request){string host=request.RequestUri!.DnsSafeHost;if(host=="codex-reset.com")return TeamHtml("2999999999999999999","Routine Codex improvements only.");if(host=="help.openai.com")return "<article><h1>Codex</h1><p>Routine improvements only.</p></article>";if(host is "openai.com" or "www.openai.com")return OfficialHtml("healthy-openai","Routine Codex improvements only.");return Feed("healthy-"+host.Replace('.','-'),"Routine Codex improvements only.");}
 static HttpResponseMessage Healthy(HttpRequestMessage request)=>new(HttpStatusCode.OK){Content=new StringContent(HealthyPayload(request),Encoding.UTF8,"text/plain")};
 sealed class SourceHandler(Func<HttpRequestMessage,HttpResponseMessage> send):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken token)=>Task.FromResult(send(request));}
}
