using System.Security.Cryptography;
using System.Text.Json;
namespace CodexUsageMonitor;

internal static class Rc4HistoryEventTests {
 static void Assert(bool value,string id){if(!value)throw new InvalidOperationException(id);}
 internal static UsageSample Sample(string id,DateTimeOffset at,decimal remaining,bool gap=false,int? banked=1,DateTimeOffset? reset=null)=>new(){
  sample_id=id,poll_id="poll-"+id,request_started_utc=at,observed_at_utc=at,observed_at_local=at.ToLocalTime(),monotonic_elapsed_ms=1,
  account_context_key="account-fixture",context_assurance="STABLE_SCOPE",source_generation="generation-fixture",codex_version="fixture",
  limit_id="codex",limit_name_safe="Weekly",source_slot="primary",window_duration_mins=10080,used_percent_raw=100-remaining,remaining_percent=remaining,
  reset_at_unix_seconds=reset?.ToUnixTimeSeconds(),reset_at_utc=reset,plan_type="plus",reset_credits_available_count=banked,
  data_quality="VALID",comparison_key="account-fixture|weekly|codex|10080",had_gap=gap,polling_interval_seconds=90};
 internal static (List<UsageSample> samples,UsageEvent focus,UsageEvent timestamp) EvidenceRows(DateTimeOffset now,bool gap=false){
  var before=Sample("before-7",now.AddSeconds(-91),7,false,1,now.AddDays(3));var after=Sample("after-100",now,100,gap,1,now.AddDays(7));
  var generated=EventDetector.Compare(before,after);return([before,after],generated.Single(x=>x.event_type=="FULL_REPLENISHMENT_OBSERVED"),generated.Single(x=>x.event_type=="RESET_TIMESTAMP_CHANGED"));
 }
 static RadarState MixedCoverage(DateTimeOffset at){var state=Rc4CoverageTests.State(6,at);foreach(int i in new[]{2,3})state.Sources[i]=state.Sources[i] with{Status="DEGRADED",LastSuccess=null,HttpStatus=403,Error="HTTP_403"};return state;}
 internal static RadarState RadarAt(DateTimeOffset at){var state=MixedCoverage(at);var historical=MixedCoverage(at.AddHours(-24));var watch=Rc4SignalPolishTests.Signal("WATCH","7300000000000000001") with{FirstSeen=at.AddHours(-24),LastSeen=at.AddHours(-24),PublishedAt=at.AddHours(-24),ReadAt=at.AddHours(-23)};state.Events=[watch];state.SignalHistory=[new(at.AddHours(-24),watch.EventId,watch.RevisionId,"WATCH",watch.Phase,watch.Effect,watch.Scope,watch.ResetUtc,watch.TimeQuality,watch.PublishedAt,watch.ReadAt,watch.Source,watch.SourceClass,watch.OriginalSourceUrl,watch.RelayUrl,watch.OriginalQuote,watch.ContentHash,watch.SignalReason,RadarCoverage.Measure(historical,true,at.AddHours(-24)))];state.CoverageTimeline=[RadarCoverage.Measure(state,true,at.AddMinutes(-2))];return state;}
 internal static void Run(string root){Directory.CreateDirectory(root);var results=new List<object>();int failed=0;var now=DateTimeOffset.UtcNow;
  void Check(string id,Action action){try{action();results.Add(new{id,result="PASS",classification="FOCUSED_PRODUCTION_PATH"});}catch(Exception ex){failed++;results.Add(new{id,result="FAIL",classification="FOCUSED_PRODUCTION_PATH",error=ex.ToString()});}}
  Check("R008 evidence is 7 to 100 plus 93 cause UNKNOWN",()=>{var d=EvidenceRows(now);var e=EventFocusEvidence.Build(d.focus,d.samples,RadarAt(now),now);Assert(e.BeforeRemaining==7&&e.AfterRemaining==100&&e.DeltaPercentagePoints==93,"quota evidence");Assert(e.Cause=="UNKNOWN"&&e.BankedResetBefore==1&&e.BankedResetAfter==1,"cause/banked");Assert(e.ResetAtBefore!=e.ResetAtAfter,"reset_at changed");Assert(e.RadarSignalLevel=="WATCH"&&e.RadarCoverage==67&&e.RadarSourceClass=="TEAM_SIGNAL_RELAY"&&e.RadarReadState=="READ"&&e.RadarEvidenceTime.HasValue&&e.RadarEvidenceTime.Value<=e.AfterSampleTime&&e.RadarCoverageTime.HasValue&&e.RadarCoverageTime.Value<=e.AfterSampleTime,"supporting radar");});
  Check("R008 duplicate same-interval events select replenishment",()=>{var d=EvidenceRows(now);var selected=EventFocusEvidence.FocusEvents([d.timestamp,d.focus]);Assert(selected.Count==1&&selected[0].event_type=="FULL_REPLENISHMENT_OBSERVED","event identity");});
  Check("R008 future Radar evidence is never back-projected",()=>{var d=EvidenceRows(now);var radar=RadarAt(now);radar.SignalHistory=[radar.SignalHistory[0] with{Timestamp=now.AddMinutes(1),CoverageAtObservation=null}];radar.Events=[];radar.CoverageTimeline=[RadarCoverage.Measure(radar,true,now.AddMinutes(1))];var e=EventFocusEvidence.Build(d.focus,d.samples,radar,now.AddMinutes(2));Assert(e.RadarSignalLevel=="NONE"&&e.RadarCoverage==null&&e.RadarEvidenceTime==null&&e.RadarCoverageTime==null,"future evidence excluded");});
  Check("R008 only complete replenishment endpoints enter Event Focus",()=>{var d=EvidenceRows(now);var decrease=d.focus with{event_type="QUOTA_DECREASE_OBSERVED",previous_remaining=100,current_remaining=7};var oneSided=d.focus with{previous_remaining=null};Assert(!EventFocusEvidence.IsEligible(decrease)&&!EventFocusEvidence.IsEligible(oneSided)&&EventFocusEvidence.FocusEvents([decrease,oneSided]).Count==0,"ineligible rows hidden");bool rejected=false;try{EventFocusEvidence.Build(decrease,d.samples,new(),now);}catch(InvalidDataException){rejected=true;}Assert(rejected,"ineligible build rejected");});
  Check("R008 gap keeps disconnected evidence semantics",()=>{var d=EvidenceRows(now,true);var e=EventFocusEvidence.Build(d.focus,d.samples,new(),now);Assert(e.HadGap&&e.ObservationInterval.Contains('/'),"gap evidence");});
  Check("R008 Full Range has 5 to 10 percent right visual padding without rows",()=>{var d=EvidenceRows(now);using var trend=new TrendView{Latest=false,Rows=d.samples};Assert(trend.DisplayRows.Count==2,"no synthetic row");Assert(trend.RightPaddingFraction>=.05&&trend.RightPaddingFraction<=.10,"right padding");Assert(trend.Range==(0,100),"full y scale");});
  Check("R008 Full Range zoom pan reset",()=>{var d=EvidenceRows(now);var more=d.samples.Concat([Sample("after-99",now.AddMinutes(2),99,false,1,now.AddDays(7))]).ToList();using var trend=new TrendView{Latest=false,Rows=more};var original=trend.Viewport;trend.ZoomFullAt(.5,true);Assert(trend.HasCustomViewport,"wheel zoom model");var zoomed=trend.Viewport;trend.PanFull(.15);Assert(trend.Viewport!=zoomed,"horizontal pan model");trend.ResetViewport();Assert(trend.Viewport==original&&!trend.HasCustomViewport,"reset viewport");});
  Check("R008 Latest Segment semantics remain isolated after replenishment",()=>{var d=EvidenceRows(now);var after=Sample("after-99",now.AddMinutes(1.5),99,false,1,now.AddDays(7));var latest=TrendView.LatestSegment(d.samples.Concat([after]));Assert(latest.Count==2&&latest[0].remaining_percent==100&&latest[1].remaining_percent==99,"latest segment");});
  Check("attention guidance is bilingual and not prediction language",()=>{var watch=Rc4SignalPolishTests.Signal("WATCH","7300000000000000002");var en=ResetRadar.Suggest(watch,7,1,false,now,null,"en-US");var zh=ResetRadar.Suggest(watch,7,1,false,now,null,"zh-TW");Assert(en.Contains("noteworthy",StringComparison.OrdinalIgnoreCase)&&en.Contains("community discussions")&&!en.Contains("guaranteed",StringComparison.OrdinalIgnoreCase),"English guidance");Assert(zh.Contains("值得注意")&&zh.Contains("社群後續討論")&&!zh.Contains("保證重置"),"zh guidance");});
  Check("EVENT_FOCUS bilingual Analysis Log and integrity",()=>{string dir=Path.Combine(root,"log-"+Guid.NewGuid().ToString("N"));AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),RadarAt(now));using var service=new MonitorService(dir);var d=EvidenceRows(now);Assert(service.History.Save(d.samples),"history save");foreach(var lang in new[]{"en-US","zh-TW"}){string output=Path.Combine(root,"event-focus-"+lang+".log");ReportExporter.Export(service,new(now.AddHours(-1),now.AddHours(1),"codex",10080),false,CancellationToken.None,output,lang,new(144,"TEST_PROVEN"));string text=File.ReadAllText(output);Assert(text.Contains("\"section\":\"EVENT_FOCUS\"")&&text.Contains("\"before_remaining\":7")&&text.Contains("\"after_remaining\":100")&&text.Contains("\"delta_percentage_points\":93")&&text.Contains("\"cause\":\"UNKNOWN\"")&&text.Contains("\"radar_coverage\":67")&&text.Contains("\"radar_evidence_time\"")&&text.Contains("\"radar_coverage_time\""),"log fields");PublicReportTests.VerifyIntegrity(output);}});
  AtomicJson.Save(Path.Combine(root,"history-event-tests.json"),new{classification="FOCUSED_PRODUCTION_PATH",exe_sha256=ReportExporter.ExeHash(),total=results.Count,failed,results});if(failed>0)Environment.ExitCode=1;
 }
 static string Sha(string path){using var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);return Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();}
 static RadarState ReadRadar(string path){if(!File.Exists(path))return new();using var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);return JsonSerializer.Deserialize<RadarState>(stream,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??new();}
 internal static void CheckCurrent(string output){string local=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"CodexUsageMonitor"),day="2026-09-12";string usage=Path.Combine(local,"history","usage_"+day+".csv"),events=Path.Combine(local,"history","events_"+day+".csv"),radarPath=Path.Combine(local,"reset_radar.json");var paths=new[]{usage,events,radarPath}.Where(File.Exists).ToArray();var beforeHash=paths.ToDictionary(x=>Path.GetFileName(x),Sha);var eventRows=Csv.Records<UsageEvent>(events).Where(x=>x.limit_id=="codex"&&x.window_duration_mins==10080&&x.previous_remaining==7&&x.current_remaining==100).ToList();var focus=eventRows.OrderBy(EventFocusEvidence.Priority).FirstOrDefault()??throw new InvalidDataException("REAL_7_TO_100_EVENT_NOT_FOUND");var ids=new[]{focus.previous_sample_id,focus.current_sample_id}.ToHashSet(StringComparer.Ordinal);var samples=Csv.Records<UsageSample>(usage).Where(x=>ids.Contains(x.sample_id)).ToList();var evidence=EventFocusEvidence.Build(focus,samples,ReadRadar(radarPath),DateTimeOffset.UtcNow);Assert(evidence.BeforeRemaining==7&&evidence.AfterRemaining==100&&evidence.DeltaPercentagePoints==93&&evidence.Cause=="UNKNOWN","REAL_EVIDENCE_MISMATCH");var afterHash=paths.ToDictionary(x=>Path.GetFileName(x),Sha);Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);AtomicJson.Save(Path.GetFullPath(output),new{classification="ACTUAL_EXISTING_HISTORY_READ_ONLY",exe_sha256=ReportExporter.ExeHash(),checked_utc=DateTimeOffset.UtcNow,event_type=evidence.EventType,before_remaining=evidence.BeforeRemaining,after_remaining=evidence.AfterRemaining,delta_percentage_points=evidence.DeltaPercentagePoints,before_sample_time=evidence.BeforeSampleTime,after_sample_time=evidence.AfterSampleTime,had_gap=evidence.HadGap,observation_interval=evidence.ObservationInterval,radar_signal_level=evidence.RadarSignalLevel,radar_coverage=evidence.RadarCoverage,radar_source_class=evidence.RadarSourceClass,radar_read_state=evidence.RadarReadState,radar_evidence_time=evidence.RadarEvidenceTime,radar_coverage_time=evidence.RadarCoverageTime,banked_reset_before=evidence.BankedResetBefore,banked_reset_after=evidence.BankedResetAfter,reset_at_before=evidence.ResetAtBefore,reset_at_after=evidence.ResetAtAfter,cause=evidence.Cause,history_source_hash_unchanged=beforeHash.All(x=>afterHash.GetValueOrDefault(x.Key)==x.Value),source_files_opened_read_only=true,state_mutated=false});}
}




