using System.Runtime.InteropServices;
using System.Text;
namespace CodexUsageMonitor;

internal static class Rc4HistoryEventNative {
 [DllImport("user32.dll")]static extern IntPtr GetThreadDesktop(uint id);
 [DllImport("kernel32.dll")]static extern uint GetCurrentThreadId();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool GetUserObjectInformation(IntPtr obj,int index,StringBuilder text,uint size,out uint needed);
 [DllImport("user32.dll")]static extern bool PrintWindow(IntPtr hwnd,IntPtr dc,uint flags);
 internal static void Attach(OverlayForm main,MonitorService mainService,string[] args){int index=Array.IndexOf(args,"--rc4-history-event-native");if(index<0)return;string output=Path.GetFullPath(args[index+1]);Directory.CreateDirectory(output);var desktop=new StringBuilder(256);GetUserObjectInformation(GetThreadDesktop(GetCurrentThreadId()),2,desktop,512,out _);if(!desktop.ToString().StartsWith("CUM_RC4_QA_",StringComparison.Ordinal))throw new InvalidOperationException("R008 native QA requires the non-input desktop.");
  main.Shown+=async(_,_)=>{main.Hide();var checks=new List<object>();var frames=new List<object>();int failures=0;
   void Check(string id,bool value,object? detail=null){if(!value)failures++;checks.Add(new{id,result=value?"PASS":"FAIL",classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",detail});AtomicJson.Save(Path.Combine(output,"checks.json"),checks);}
   async Task Capture(Form form,string name){if(!form.Visible)form.Show();for(int i=0;i<6;i++){await Task.Delay(80);Application.DoEvents();}form.Invalidate(true);form.Refresh();using var bitmap=new Bitmap(form.Width,form.Height);using(var g=Graphics.FromImage(bitmap)){var dc=g.GetHdc();try{if(!PrintWindow(form.Handle,dc,2))throw new InvalidOperationException("PrintWindow failed");}finally{g.ReleaseHdc(dc);}if(form is ProductForm product)foreach(var button in product.AllControls().OfType<QuietButton>().Where(x=>x.Visible)){using var image=new Bitmap(button.Width,button.Height);button.DrawToBitmap(image,new(Point.Empty,button.Size));var pt=button.PointToScreen(Point.Empty);g.DrawImageUnscaled(image,pt.X-form.Left,pt.Y-form.Top);}}string path=Path.Combine(output,name+".png");bitmap.Save(path);frames.Add(new{name,path=Path.GetFileName(path),dpi=form.DeviceDpi,width=form.Width,height=form.Height,desktop=desktop.ToString(),input_desktop_switched=false});}
   MonitorService Fixture(string name,bool gap,bool radar,out string afterId){string dir=Path.Combine(output,"data-"+name);var now=DateTimeOffset.UtcNow;if(radar)AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),Rc4HistoryEventTests.RadarAt(now));var service=new MonitorService(dir);var before=Rc4HistoryEventTests.Sample(name+"-before",now.AddMinutes(-6),7,false,1,now.AddDays(3));var after=Rc4HistoryEventTests.Sample(name+"-after",now.AddMinutes(-4.5),100,gap,1,now.AddDays(7));var tail=Rc4HistoryEventTests.Sample(name+"-tail",now.AddMinutes(-3),99,false,1,now.AddDays(7));service.History.Save([before,after,tail]);afterId=after.sample_id;return service;}
   try{
    L.SetLanguage("zh-TW");using(var service=Fixture("main",false,false,out var eventId)){using var history=new HistoryForm(service);history.Show();for(int i=0;i<10;i++){await Task.Delay(80);Application.DoEvents();}
     history.SetChartMode(false);await Capture(history,"V39-full-range-right-padding-zh-TW");Check("V39 Full Range right padding and no synthetic sample",history.TrendForTest.RightPaddingFraction>=.05&&history.TrendForTest.RightPaddingFraction<=.10&&history.ChartRows.Count==3,new{history.TrendForTest.RightPaddingFraction,rows=history.ChartRows.Count});
     Check("V40 Event Focus opens from product History",history.OpenEventFocusForSample(eventId));await Capture(history,"V40-event-focus-7-to-100-zh-TW");Check("V40 exact event evidence",history.FocusEvidence is {BeforeRemaining:7,AfterRemaining:100,DeltaPercentagePoints:93,Cause:"UNKNOWN",HadGap:false},history.FocusEvidence);
     history.SetChartMode(false);history.TrendForTest.ZoomFullAt(.56,true);history.TrendForTest.PanFull(.12);await Capture(history,"V43-full-range-pan-zoom-zh-TW");Check("V43 pan and zoom viewport",history.TrendForTest.HasCustomViewport,history.TrendForTest.Viewport);
     history.SetChartMode(true);await Capture(history,"V44-latest-segment-regression-zh-TW");Check("V44 Latest Segment excludes pre-replenishment segment",history.ChartRows.Count==2&&history.ChartRows[0].remaining_percent==100&&history.ChartRows[1].remaining_percent==99,new{rows=history.ChartRows.Count});history.Close();}
    L.SetLanguage("en-US");using(var service=Fixture("radar",false,true,out var eventId)){using var history=new HistoryForm(service);history.Show();for(int i=0;i<10;i++){await Task.Delay(80);Application.DoEvents();}Check("V41 Event Focus opens",history.OpenEventFocusForSample(eventId));await Capture(history,"V41-event-focus-watch-context-en-US");Check("V41 WATCH context remains supporting evidence",history.FocusEvidence is {RadarSignalLevel:"WATCH",RadarCoverage:67,RadarSourceClass:"TEAM_SIGNAL_RELAY",RadarReadState:"READ",Cause:"UNKNOWN"},history.FocusEvidence);history.Close();}
    using(var service=Fixture("gap",true,false,out var eventId)){using var history=new HistoryForm(service);history.Show();for(int i=0;i<10;i++){await Task.Delay(80);Application.DoEvents();}Check("V42 Event Focus opens",history.OpenEventFocusForSample(eventId));await Capture(history,"V42-event-focus-observation-gap-en-US");Check("V42 gap uses separated observation semantics",history.FocusEvidence?.HadGap==true,history.FocusEvidence);history.Close();}
    foreach(var language in new[]{"en-US","zh-TW"}){L.SetLanguage(language);string dir=Path.Combine(output,"data-guidance-"+language);AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),Rc4HistoryEventTests.RadarAt(DateTimeOffset.UtcNow));using var service=new MonitorService(dir);using var page=new ResetInfoForm(service,service.Radar.ActiveSignal);page.Show();await Task.Delay(300);Application.DoEvents();page.ScrollSuggestionForTest();await Capture(page,"W"+(language=="en-US"?"45":"46")+"-watch-attention-guidance-"+language);string shown=page.DisplayedSuggestion;Check("WATCH attention guidance "+language,language=="en-US"?shown.Contains("community discussions")&&shown.Contains("There is no need to spend quota"):shown.Contains("社群後續討論")&&shown.Contains("不需因目前訊號刻意消耗額度"),shown);page.Close();}
   }catch(Exception ex){failures++;File.WriteAllText(Path.Combine(output,"error.txt"),ex.ToString());}
   finally{AtomicJson.Save(Path.Combine(output,"complete.json"),new{classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",exe_sha256=ReportExporter.ExeHash(),total=checks.Count,failed=failures,frames,input_desktop_switched=false});Environment.ExitCode=failures==0?0:1;main.Close();Application.Exit();}
  };
 }
}
