using System.Runtime.InteropServices;
using System.Text;
namespace CodexUsageMonitor;

internal static class Rc4SignalPolishNative {
 [DllImport("user32.dll")] static extern IntPtr GetThreadDesktop(uint id);
 [DllImport("kernel32.dll")] static extern uint GetCurrentThreadId();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern bool GetUserObjectInformation(IntPtr obj,int index,StringBuilder text,uint size,out uint needed);
 [DllImport("user32.dll")] static extern bool PrintWindow(IntPtr window,IntPtr dc,uint flags);
 public static void Attach(OverlayForm main,MonitorService mainService,string[] args){int index=Array.IndexOf(args,"--rc4-signal-polish-native");if(index<0)return;string output=Path.GetFullPath(args[index+1]);Directory.CreateDirectory(output);var desktop=new StringBuilder(256);GetUserObjectInformation(GetThreadDesktop(GetCurrentThreadId()),2,desktop,512,out _);if(!desktop.ToString().StartsWith("CUM_RC4_QA_",StringComparison.Ordinal))throw new InvalidOperationException("Signal polish native QA requires the non-input desktop.");
  var checks=new List<object>();var frames=new List<object>();int failures=0;
  void Check(string id,bool value,object? detail=null){if(!value)failures++;checks.Add(new{id,result=value?"PASS":"FAIL",classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",detail});AtomicJson.Save(Path.Combine(output,"checks.json"),checks);}
  main.Shown+=async(_,_)=>{try{main.Hide();
   async Task<(Bitmap image,string path)> Capture(Form form,string name){if(!form.Visible)form.Show();await Task.Delay(240);form.Invalidate(true);form.Refresh();Application.DoEvents();using(var warm=new Bitmap(form.Width,form.Height))using(var g=Graphics.FromImage(warm)){var dc=g.GetHdc();try{PrintWindow(form.Handle,dc,2);}finally{g.ReleaseHdc(dc);}}await Task.Delay(80);var image=new Bitmap(form.Width,form.Height);using(var g=Graphics.FromImage(image)){var dc=g.GetHdc();try{if(!PrintWindow(form.Handle,dc,2))throw new InvalidOperationException("PrintWindow failed");}finally{g.ReleaseHdc(dc);}}string path=Path.Combine(output,name+".png");image.Save(path);frames.Add(new{name,path=Path.GetFileName(path),dpi=form.DeviceDpi,width=form.Width,height=form.Height,desktop=desktop.ToString(),input_desktop_switched=false});return(image,path);}
   int Count(Bitmap image,Rectangle bounds,Color color){bounds.Intersect(new(Point.Empty,image.Size));int count=0;for(int y=bounds.Top;y<bounds.Bottom;y++)for(int x=bounds.Left;x<bounds.Right;x++)if(image.GetPixel(x,y).ToArgb()==color.ToArgb())count++;return count;}
   var scenarios=new[]{("weekly-13-no-radar","13%","NONE"),("weekly-13-watch","13%","WATCH"),("weekly-13-incoming","13%","INCOMING"),("weekly-3-watch","3%","WATCH"),("weekly-3-incoming","3%","INCOMING")};Rectangle? stableBadge=null;
   foreach(var (name,weekly,level) in scenarios){L.SetLanguage("en-US");using var service=new MonitorService(Path.Combine(output,"data-"+name));if(level!="NONE")service.Radar.Apply([Rc4SignalPolishTests.Signal(level,level=="WATCH"?name.EndsWith("13-watch")?"5100000000000000001":"5100000000000000003":name.EndsWith("13-incoming")?"5100000000000000002":"5100000000000000004")],DateTimeOffset.UtcNow);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly=weekly,TestAge="8s",TestCountdownTip=L.T("Overlay.CountdownNormal",8),TestRadarCoverage="67%"};overlay.Render();var (image,_)=await Capture(overlay,name);using(image){float k=overlay.UiScale;var weeklyArea=Rectangle.Round(new RectangleF(22*k,13*k,112*k,46*k));var badge=overlay.RadarBadgeBounds;stableBadge??=badge;int quotaWarning=Count(image,weeklyArea,Theme.Warning),quotaCritical=Count(image,weeklyArea,Theme.Critical),watchBadge=Count(image,badge,Theme.Warning),incomingBadge=Count(image,badge,Theme.ResetAlert);bool critical=weekly=="3%";Check(name+" quota color is independent",critical?quotaCritical>8&&quotaWarning==0:quotaWarning>8&&quotaCritical==0,new{quotaWarning,quotaCritical});Check(name+" fixed badge bounds",stableBadge==badge&&badge.Right<=overlay.ClientSize.Width&&badge.Top==3,new{badge,overlay.ClientSize});Check(name+" signal badge semantics",level switch{"NONE"=>watchBadge==0&&incomingBadge==0,"WATCH"=>watchBadge>20&&incomingBadge==0,"INCOMING"=>incomingBadge>20&&watchBadge==0,_=>false},new{watchBadge,incomingBadge});Check(name+" Compact remains 156x88 DIP",overlay.ClientSize==new Size((int)(156*k),(int)(88*k)));}
    if(name=="weekly-13-watch"){using var page=new ResetInfoForm(service,service.Radar.Unread);page.Show();await Task.Delay(300);Application.DoEvents();overlay.Render();Check("read event keeps active marker",service.Radar.Unread==null&&overlay.RadarSignalLevel=="WATCH"&&!overlay.RadarSignalUnread&&overlay.DisplayText.StartsWith("13%"));page.Close();}
    overlay.Close();
   }
   using(var watchService=new MonitorService(Path.Combine(output,"tooltip-watch"))){watchService.Radar.Apply([Rc4SignalPolishTests.Signal("WATCH","5100000000000000005")],DateTimeOffset.UtcNow);using var overlay=new OverlayForm(watchService,true);L.SetLanguage("en-US");string en=overlay.RadarTooltip;L.SetLanguage("zh-TW");string zh=overlay.RadarTooltip;Check("WATCH unread bilingual tooltip",en=="New Reset Watch"&&zh=="新的重置觀察訊號",new{en,zh});}
   using(var incomingService=new MonitorService(Path.Combine(output,"tooltip-incoming"))){incomingService.Radar.Apply([Rc4SignalPolishTests.Signal("INCOMING","5100000000000000006")],DateTimeOffset.UtcNow);using var overlay=new OverlayForm(incomingService,true);L.SetLanguage("en-US");string en=overlay.RadarTooltip;L.SetLanguage("zh-TW");string zh=overlay.RadarTooltip;Check("INCOMING unread bilingual tooltip",en=="New Reset Incoming"&&zh=="新的重置即將發生訊號",new{en,zh});}
   L.SetLanguage("en-US");const string completedText="Codex global reset has been applied for all paid plans.";var completed=Rc4SignalPolishTests.Signal("INCOMING","5100000000000000007") with{SignalLevel="COMPLETED",Phase="COMPLETED",ResetUtc=DateTimeOffset.UtcNow,Summary=completedText,OriginalQuote=completedText};using(var service=new MonitorService(Path.Combine(output,"completed"))){service.Radar.Apply([completed],DateTimeOffset.UtcNow);using var page=new ResetInfoForm(service,service.Radar.Snapshot().Events.Single());Check("completed card uses success teal",page.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.Accent);var (image,_)=await Capture(page,"radar-completed-teal");image.Dispose();page.Close();}
   var quota=R004Tests.Rows(74,100);var observed=completed with{EventId="native-observed",RevisionId="native-observed-r",ResetUtc=quota[1].observed_at_utc};using(var service=new MonitorService(Path.Combine(output,"observed"))){service.Radar.Apply([observed],quota[1].observed_at_utc);service.Radar.Correlate(quota);using var page=new ResetInfoForm(service,service.Radar.Snapshot().Events.Single());Check("locally observed card uses success teal",page.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.Accent);var (image,_)=await Capture(page,"radar-locally-observed-teal");image.Dispose();page.Close();}
  }catch(Exception ex){failures++;File.WriteAllText(Path.Combine(output,"error.txt"),ex.ToString());}finally{AtomicJson.Save(Path.Combine(output,"complete.json"),new{classification="ACTUAL_NATIVE_NON_INPUT_DESKTOP",exe_sha256=ReportExporter.ExeHash(),total=checks.Count,failed=failures,frames,input_desktop_switched=false});Environment.ExitCode=failures==0?0:1;main.Close();Application.Exit();}};
 }
}
