using System.Net;
using System.Text.Json;
namespace CodexUsageMonitor;

internal static class Rc4SignalPolishTests {
 static DateTimeOffset Now=>DateTimeOffset.UtcNow;
 internal static Announcement Signal(string level,string id="5000000000000000001"){
  string body=level=="WATCH"?"When I say excellent service for existing Codex users, that includes the occasional reset.":"Codex global reset will be applied tomorrow around 6 PM PT for all paid plans.";
  string html="<ul><li class=\"feed-item\"><p class=\"feed-text\">"+WebUtility.HtmlEncode(body)+"</p><a href=\"https://x.com/thsottiaux/status/"+id+"\">original</a><a class=\"feed-time\">1h ago</a></li></ul>";
  var value=Rc4Radar.Parse(ResetRadar.Sources.Single(x=>x.Id=="team-codex-reset"),html,Now,out _).Single();
  if(value.SignalLevel!=level)throw new InvalidOperationException("Signal fixture mismatch");return value;
 }
 internal static void Run(string root){Directory.CreateDirectory(root);var rows=new List<object>();int failed=0;
  void Check(string id,Action action){try{action();rows.Add(new{id,result="PASS",classification="FOCUSED_PRODUCTION_PATH"});}catch(Exception ex){failed++;rows.Add(new{id,result="FAIL",classification="FOCUSED_PRODUCTION_PATH",error=ex.ToString()});}}
  void Assert(bool value,string id){if(!value)throw new InvalidOperationException(id);}
  Check("quota thresholds are signal-independent",()=>{Assert(Theme.QuotaColor(21)==Theme.Text,"21 normal");Assert(Theme.QuotaColor(20)==Theme.Warning&&Theme.QuotaColor(13)==Theme.Warning,"warning");Assert(Theme.QuotaColor(5)==Theme.Critical&&Theme.QuotaColor(3)==Theme.Critical&&Theme.QuotaColor(0)==Theme.Critical,"critical");});
  Check("fixed badge bounds do not depend on Weekly width",()=>{using var service=new MonitorService(Path.Combine(root,"bounds"));service.Radar.Apply([Signal("WATCH")],Now);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly="3%"};overlay.Render();var first=overlay.RadarBadgeBounds;overlay.TestWeekly="100%";overlay.Render();Assert(first==overlay.RadarBadgeBounds&&first.X>overlay.ClientSize.Width-24*overlay.UiScale,"fixed top right");});
  Check("exact bilingual signal tooltips",()=>{using var watchService=new MonitorService(Path.Combine(root,"tip-watch"));var watchItem=Signal("WATCH","5000000000000000002");watchService.Radar.Apply([watchItem],Now);using var watch=new OverlayForm(watchService,true);L.SetLanguage("en-US");Assert(watch.RadarTooltip=="New Reset Watch","watch unread en");L.SetLanguage("zh-TW");Assert(watch.RadarTooltip=="新的重置觀察訊號","watch unread zh");watchService.Radar.Read(watchItem.EventId,watchItem.RevisionId);L.SetLanguage("en-US");Assert(watch.RadarTooltip=="Reset Watch — already viewed, signal still active","watch read en");L.SetLanguage("zh-TW");Assert(watch.RadarTooltip=="重置觀察 — 已查看，訊號仍有效","watch read zh");using var incomingService=new MonitorService(Path.Combine(root,"tip-incoming"));var incomingItem=Signal("INCOMING","5000000000000000003");incomingService.Radar.Apply([incomingItem],Now);using var incoming=new OverlayForm(incomingService,true);L.SetLanguage("en-US");Assert(incoming.RadarTooltip=="New Reset Incoming","incoming unread en");incomingService.Radar.Read(incomingItem.EventId,incomingItem.RevisionId);Assert(incoming.RadarTooltip=="Reset Incoming — already viewed, still active","incoming read en");L.SetLanguage("zh-TW");Assert(incoming.RadarTooltip=="重置即將發生 — 已查看，訊號仍有效","incoming read zh");});
  Check("read state keeps active signal without quota mutation",()=>{using var service=new MonitorService(Path.Combine(root,"read"));var item=Signal("WATCH","5000000000000000004");service.Radar.Apply([item],Now);service.Settings.Compact=true;using var overlay=new OverlayForm(service,true){TestWeekly="13%"};overlay.Render();Assert(overlay.RadarSignalLevel=="WATCH"&&overlay.RadarSignalUnread,"unread shown");service.Radar.Read(item.EventId,item.RevisionId);overlay.Render();Assert(overlay.RadarSignalLevel=="WATCH"&&!overlay.RadarSignalUnread&&overlay.DisplayText.StartsWith("13%"),"read keeps active marker");Assert(Theme.QuotaColor(13)==Theme.Warning,"quota retained");});
  Check("completed and locally observed pages use success teal",()=>{const string completedText="Codex global reset has been applied for all paid plans.";var complete=Signal("INCOMING","5000000000000000005") with{SignalLevel="COMPLETED",Phase="COMPLETED",ResetUtc=Now,Summary=completedText,OriginalQuote=completedText};string a=Path.Combine(root,"completed");using(var service=new MonitorService(a)){service.Radar.Apply([complete],Now);using var page=new ResetInfoForm(service,service.Radar.Snapshot().Events.Single());Assert(page.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.Accent,"completed teal");}string b=Path.Combine(root,"observed");var rows2=R004Tests.Rows(74,100);var observed=complete with{EventId="observed",RevisionId="observed-r",ResetUtc=rows2[1].observed_at_utc};using(var service=new MonitorService(b)){service.Radar.Apply([observed],rows2[1].observed_at_utc);service.Radar.Correlate(rows2);using var page=new ResetInfoForm(service,service.Radar.Snapshot().Events.Single());Assert(page.AllControls().OfType<RadarAccentPanel>().Single().Accent==Theme.Accent,"observed teal");}});
  AtomicJson.Save(Path.Combine(root,"signal-polish-tests.json"),new{classification="FOCUSED_PRODUCTION_PATH",exe_sha256=ReportExporter.ExeHash(),total=rows.Count,failed,rows});if(failed>0)Environment.ExitCode=1;
 }
}
