using System.Runtime.InteropServices;
using System.Reflection;
using System.Text;
namespace CodexUsageMonitor;
internal static class RedesignNative {
 [DllImport("user32.dll")]static extern IntPtr GetThreadDesktop(uint id);
 [DllImport("kernel32.dll")]static extern uint GetCurrentThreadId();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool GetUserObjectInformation(IntPtr obj,int index,StringBuilder text,uint size,out uint needed);
 [DllImport("user32.dll")]static extern bool PrintWindow(IntPtr hwnd,IntPtr dc,uint flags);
 [DllImport("user32.dll")]static extern IntPtr SendMessage(IntPtr hwnd,uint msg,IntPtr wp,IntPtr lp);
 [DllImport("user32.dll")]static extern IntPtr SetActiveWindow(IntPtr window);
 [DllImport("user32.dll")]static extern IntPtr GetActiveWindow();
 [DllImport("user32.dll")]static extern IntPtr GetFocus();
 [DllImport("user32.dll")]static extern void NotifyWinEvent(uint id,IntPtr window,int obj,int child);
 [DllImport("user32.dll")]static extern int GetWindowLong(IntPtr hwnd,int index);
 [DllImport("user32.dll")]static extern uint GetDpiForWindow(IntPtr hwnd);
 internal static void Attach(OverlayForm main,MonitorService unused,string[] args){int at=Array.IndexOf(args,"--redesign-native");if(at<0)return;string output=Path.GetFullPath(args[at+1]);Directory.CreateDirectory(output);var desktop=new StringBuilder(256);GetUserObjectInformation(GetThreadDesktop(GetCurrentThreadId()),2,desktop,512,out _);if(!desktop.ToString().StartsWith("CUM_RC4_QA_"))throw new InvalidOperationException("Non-input desktop required");
  main.Shown+=async(_,_)=>{main.Hide();var checks=new List<object>();var frames=new List<object>();int failed=0;
   void Check(string id,bool ok,object? detail=null){if(!ok)failed++;checks.Add(new{id,result=ok?"PASS":"FAIL",detail});AtomicJson.Save(Path.Combine(output,"checks.json"),checks);}
   async Task Pump(){for(int i=0;i<4;i++){await Task.Delay(80);Application.DoEvents();}}
   async Task Capture(Form f,string name){if(!f.Visible)f.Show();await Pump();f.Invalidate(true);f.Refresh();using var image=new Bitmap(f.Width,f.Height);using(var g=Graphics.FromImage(image)){var dc=g.GetHdc();try{if(!PrintWindow(f.Handle,dc,2))throw new IOException("PrintWindow");}finally{g.ReleaseHdc(dc);}}
    image.Save(Path.Combine(output,name+".png"));frames.Add(new{name,dpi=f.DeviceDpi,width=f.Width,height=f.Height,classification="NATIVE_SYNTHETIC_ISOLATED",input_desktop_switched=false});
   }
   async Task Dpi125(Form f,string name){f.Show();await Pump();var before=f.DeviceDpi;int monitor=(int)GetDpiForWindow(f.Handle);var rect=f.Bounds;float ratio=120f/before;var data=new[]{rect.Left,rect.Top,rect.Left+(int)(rect.Width*ratio),rect.Top+(int)(rect.Height*ratio)};var ptr=Marshal.AllocHGlobal(16);try{Marshal.Copy(data,0,ptr,4);SendMessage(f.Handle,0x02E0,new IntPtr(120|(120<<16)),ptr);}finally{Marshal.FreeHGlobal(ptr);}await Capture(f,name);Check("120 DPI parent-message simulation received "+name,f.DeviceDpi==120,new{before,managed_dpi=f.DeviceDpi,monitor_dpi=monitor,classification="PRIVATE_NATIVE_WM_DPICHANGED_SIMULATION_NOT_PHYSICAL_125_MONITOR"});f.Close();}
   void Click(ProductForm f,string key)=>f.AllControls().OfType<Button>().Single(b=>b.Text==L.T(key)).PerformClick();
   MonitorService Fixture(string name,string level="WATCH"){string dir=Path.Combine(output,"data-"+name);var now=DateTimeOffset.UtcNow;var state=Rc4HistoryEventTests.RadarAt(now);state.Events=[];state.SignalHistory=[];if(level!="NONE"){var a=Rc4SignalPolishTests.Signal(level=="COMPLETED"?"INCOMING":level);if(level=="COMPLETED")a=a with{SignalLevel="COMPLETED",Phase="COMPLETED",ResetUtc=now,Summary="Codex global reset has been applied.",OriginalQuote="Codex global reset has been applied."};state.Events=[a];}
    AtomicJson.Save(Path.Combine(dir,"reset_radar.json"),state);
    AtomicJson.Save(Path.Combine(dir,"last_good.json"),new Snapshot(now,now,0,"synthetic","FIXTURE","fixture","fixture",[new("codex","Weekly","primary",10080,87,now.AddDays(6).ToUnixTimeSeconds(),"VALID","plus",null,null,null,"")],1,[]));
    var s=new MonitorService(dir);s.Settings.UiLanguage=L.Language;s.Settings.TopMost=true;var samples=new List<UsageSample>();for(int i=0;i<10;i++)samples.Add(Rc4HistoryEventTests.Sample("pre-"+i,now.AddMinutes(-30+i*2),25-i*2));samples.Add(Rc4HistoryEventTests.Sample("after-100",now.AddMinutes(-10.5),100));samples.Add(Rc4HistoryEventTests.Sample("after-99",now.AddMinutes(-9),99));s.History.Save(samples);return s;
   }
   try{
    if(output.Contains("representative")){foreach(string lang in new[]{"en-US","zh-TW"}){L.SetLanguage(lang);using var s=Fixture("rep-"+lang);using(var h=new HistoryForm(s)){h.Show();await h.LoadPage();h.SetChartMode(false);await Capture(h,"history-"+lang);h.OpenEventFocusForSample("after-100");await Capture(h,"event-focus-"+lang);h.Close();}using(var f=new SettingsForm(s)){await Capture(f,"settings-"+lang);L.SetLanguage(lang=="en-US"?"zh-TW":"en-US");L.SetLanguage(lang);Check("Custom chrome live bilingual accessibility "+lang,f.AllControls().OfType<R2WindowButton>().Select(x=>x.AccessibleName).Order().SequenceEqual((lang=="zh-TW"?new[]{"最小化視窗","最大化或還原視窗","關閉視窗"}:new[]{"Minimize window","Maximize or restore window","Close window"}).Order()));var max=f.AllControls().OfType<R2WindowButton>().Single(x=>x.Text=="□");max.PerformClick();await Pump();Check("Custom chrome maximize "+lang,f.WindowState==FormWindowState.Maximized);max.PerformClick();await Pump();Check("Custom chrome restore "+lang,f.WindowState==FormWindowState.Normal);Click(f,"Settings.AdvancedSource");await Capture(f,"settings-advanced-"+lang);var field=f.AllControls().OfType<TextBox>().Single();Check("Advanced source within column "+lang,field.Right<=field.Parent!.Width&&field.Visible);Click(f,"Settings.AdvancedSource");Check("Advanced source collapse "+lang,!field.Visible);f.Close();}using(var f=new ResetInfoForm(s,s.Radar.ActiveSignal)){await Capture(f,"radar-watch-"+lang);f.Close();}}using(var s=Fixture("dpi120")){using(var f=new SettingsForm(s))await Dpi125(f,"settings-125-simulated");using(var f=new HistoryForm(s)){f.Show();await f.LoadPage();await Dpi125(f,"history-125-simulated");}using(var f=new ResetInfoForm(s,s.Radar.ActiveSignal))await Dpi125(f,"radar-125-simulated");}Check("Native representatives rendered",frames.Count==13);}
    else {
    foreach(string lang in new[]{"en-US","zh-TW"}){L.SetLanguage(lang);using var s=Fixture(lang);using var hud=new OverlayForm(s,true){TestWeekly="13%",TestAge="57s",TestCountdownTip=L.T("Overlay.CountdownNormal",57),TestRadarCoverage="67%",TestDays=["≈3%","≈12%","≈6%"]};s.Settings.Compact=true;hud.Show();hud.Render();await Capture(hud,"compact-unread-"+lang);Check("Compact 156x88 DIP "+lang,hud.ClientSize==new Size((int)(156*hud.UiScale),(int)(88*hud.UiScale)));hud.ToggleMode();await Capture(hud,"standard-"+lang);Check("Standard 330x84 DIP "+lang,hud.ClientSize==new Size((int)(330*hud.UiScale),(int)(84*hud.UiScale)));using(var measure=hud.CreateGraphics()){using var font=Theme.PixelFont(lang=="en-US"?7.5f:8f);Check("Standard labels fit single line "+lang,Enumerable.Range(0,3).All(i=>measure.MeasureString(OverlayForm.DayName(i),font).Width<=(lang=="zh-TW"?34:i==0?36:i==1?54:58)));}Check("Countdown semantics "+lang,hud.CountdownText=="57s"&&hud.CountdownTooltip==L.T("Overlay.CountdownNormal",57));hud.Hide();
     using(var h=new HistoryForm(s)){h.Show();await h.LoadPage();h.SetChartMode(false);await Capture(h,"history-full-"+lang);Check("History table taller "+lang,h.AllControls().OfType<DataGridView>().Single().Height>=250*h.DeviceDpi/96f);Check("Event Focus opens "+lang,h.OpenEventFocusForSample("after-100"));await Capture(h,"history-event-focus-"+lang);Check("Event 7 to100 preserved "+lang,h.FocusEvidence is{BeforeRemaining:7,AfterRemaining:100,Cause:"UNKNOWN"});Check("Exactly one chart mode selected "+lang,h.AllControls().OfType<QuietButton>().Count(b=>b.Selected)==1);h.SetChartMode(true);await Capture(h,"history-latest-"+lang);await h.ExportCsv();Check("Formal CSV exported "+lang,h.LastExport!=null);if(h.LastExport!=null)File.Copy(h.LastExport,Path.Combine(output,"ui-example-"+lang+".csv"),true);h.Close();}
     using(var settings=new SettingsForm(s,hud)){settings.Show();await Pump();await Capture(settings,"settings-"+lang);var body=settings.Controls.OfType<Panel>().First(p=>p.AutoScroll);body.ScrollControlIntoView(settings.AllControls().OfType<Button>().Single(b=>b.Text==L.T("Settings.CheckConnection")));await Capture(settings,"settings-lower-"+lang);int settingsBefore=body.DisplayRectangle.Height;Click(settings,"Settings.AdvancedSource");await Pump();var path=settings.AllControls().OfType<TextBox>().Single();body.ScrollControlIntoView(path);await Capture(settings,"settings-advanced-"+lang);Check("Settings expansion stays within column "+lang,path.Visible&&path.Right<=path.Parent!.ClientSize.Width);Click(settings,"Settings.AdvancedSource");await Pump();Check("Settings collapse restores height "+lang,body.DisplayRectangle.Height==settingsBefore);settings.AllControls().OfType<OpacitySlider>().Single().Value=85;Click(settings,"Settings.Cancel");Check("Cancel restores opacity "+lang,s.Settings.OpacityPercent==70&&Math.Abs(hud.Opacity-.7)<.01);}
     using(var details=new DetailsForm(s)){await Capture(details,"details-"+lang);var body=details.Controls.OfType<Panel>().First(p=>p.AutoScroll);int before=body.DisplayRectangle.Height;Click(details,"Details.OtherPools");Click(details,"Details.Advanced");await Pump();await Capture(details,"details-expanded-"+lang);Check("Details expansion reflows "+lang,body.DisplayRectangle.Height>before);Click(details,"Details.OtherPools");Click(details,"Details.Advanced");await Pump();Check("Details collapse restores height "+lang,body.DisplayRectangle.Height==before);details.Close();}
     foreach(string level in new[]{"NONE","WATCH","INCOMING","COMPLETED"}){using var rs=Fixture(lang+level,level);using var page=new ResetInfoForm(rs,rs.Radar.Snapshot().Events.FirstOrDefault());await Capture(page,"radar-"+level.ToLowerInvariant()+"-"+lang);if(level=="NONE")Check("No signal retains populated quota card "+lang,page.AllControls().OfType<R2Card>().Where(c=>c.Visible).All(c=>c.Controls.OfType<Label>().Any(l=>!string.IsNullOrWhiteSpace(l.Text))));if(level=="INCOMING"){var summary=page.AllControls().OfType<Label>().Single(x=>x.Text==L.T("Radar.StatusIncomingSummary"));int measured=TextRenderer.MeasureText(summary.Text,summary.Font,new Size(summary.Width,int.MaxValue),TextFormatFlags.WordBreak|TextFormatFlags.TextBoxControl).Height;Check("Full INCOMING qualifier visible "+lang,summary.Height>=measured,new{summary.Text,summary.Height,measured});}if(level!="NONE"){page.ScrollSuggestionForTest();await Capture(page,"radar-card-"+level.ToLowerInvariant()+"-"+lang);Check("Radar card color "+level+lang,page.AllControls().OfType<RadarAccentPanel>().Single().Accent==(level=="WATCH"?Theme.Warning:level=="INCOMING"?Theme.ResetAlert:Theme.Accent));}
      if(level=="WATCH"){var sourceBody=page.Controls.OfType<Panel>().First(p=>p.AutoScroll);int before=sourceBody.DisplayRectangle.Height;Click(page,"Radar.ShowDetails");await Pump();var expanded=page.AllControls().OfType<Label>().Single(x=>x.Text.Contains("https://codex-reset.com/tibo"));sourceBody.ScrollControlIntoView(expanded);await Capture(page,"radar-source-details-"+lang);int measure=TextRenderer.MeasureText(expanded.Text,expanded.Font,new Size(expanded.Width,int.MaxValue),TextFormatFlags.WordBreak|TextFormatFlags.TextBoxControl).Height;Check("Radar source expansion fits "+lang,sourceBody.DisplayRectangle.Height>before&&expanded.Height>=measure);Click(page,"Radar.HideDetails");await Pump();Check("Radar source collapse restores height "+lang,sourceBody.DisplayRectangle.Height==before);Click(page,"Radar.ShowHow");var body=page.Controls.OfType<Panel>().First(p=>p.AutoScroll);body.AutoScrollPosition=new Point(0,body.VerticalScroll.Maximum);await Capture(page,"radar-explanation-"+lang);}
      page.Close();}
     using(var page=new ResetInfoForm(s,s.Radar.ActiveSignal)){page.Show();await Pump();page.Close();}hud.Show();s.Settings.Compact=true;hud.Render();await Capture(hud,"compact-read-active-"+lang);Check("Read active keeps dot "+lang,hud.RadarSignalLevel=="WATCH"&&!hud.RadarSignalUnread);hud.Close();
     using(var export=new ExportForm(s,new(DateTimeOffset.Now.AddDays(-1),DateTimeOffset.Now))){export.Show();export.ExportButton.PerformClick();for(int i=0;i<100&&export.LastExport==null;i++)await Task.Delay(100);Check("Formal Analysis Log "+lang,export.LastExport!=null);if(export.LastExport!=null)File.Copy(export.LastExport,Path.Combine(output,"ui-example-"+lang+".log"),true);await Capture(export,"export-"+lang);export.Close();}
    }
    foreach(string level in new[]{"NONE","WATCH","INCOMING"}){using var s=Fixture("compact-final-"+level,level);s.Settings.Compact=true;using var hud=new OverlayForm(s,true){TestWeekly="13%",TestAge="57s",TestRadarCoverage="67%"};await Capture(hud,"compact-"+level.ToLowerInvariant()+"-final");Check("Compact signal "+level,level=="NONE"?hud.RadarSignalLevel=="NONE":hud.RadarSignalLevel==level);hud.Close();}
    using(var form=new ProductForm("Native scrollbar interaction",700,400)){var body=form.Controls.OfType<Panel>().First(p=>p.AutoScroll);using var grid=new R2Grid{Dock=DockStyle.Fill,AllowUserToAddRows=false};grid.Columns.Add("sample","Sample");for(int i=0;i<200;i++)grid.Rows.Add("Record "+i);body.Controls.Add(grid);form.Show();await Pump();var flags=BindingFlags.Instance|BindingFlags.NonPublic;bool stable=true;foreach(int first in new[]{0,80,180}){grid.FirstDisplayedScrollingRowIndex=first;var rail=(RectangleF)typeof(R2Grid).GetMethod("Rail",flags)!.Invoke(grid,null)!;int x=(int)(rail.Left+rail.Width/2),y=(int)(rail.Top+rail.Height*.75);typeof(R2Grid).GetMethod("OnMouseDown",flags)!.Invoke(grid,[new MouseEventArgs(MouseButtons.Left,1,x,y,0)]);stable&=grid.FirstDisplayedScrollingRowIndex==first;typeof(R2Grid).GetMethod("OnMouseMove",flags)!.Invoke(grid,[new MouseEventArgs(MouseButtons.Left,0,x,y,0)]);stable&=grid.FirstDisplayedScrollingRowIndex==first;typeof(R2Grid).GetMethod("OnMouseUp",flags)!.Invoke(grid,[new MouseEventArgs(MouseButtons.Left,1,x,y,0)]);}Check("Scrollbar thumb grab preserves row before movement",stable);await Capture(form,"scrollbar-native-grab");form.Close();}
    // Actual native control states, using control events on the private desktop only.
    L.SetLanguage("en-US");using(var states=new ProductForm("Native interaction states",700,400)){var panel=states.Controls.OfType<Panel>().First(p=>p.AutoScroll);var row=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown};panel.Controls.Add(row);foreach(var state in new[]{"Primary","Secondary","Ghost","Selected","Disabled","Disabled primary","Hover","Pressed","Keyboard focus"}){var b=(QuietButton)Theme.Button(state);b.Width=240;b.Primary=state is "Primary" or "Disabled primary";b.Role=state=="Ghost"?ButtonRole.Ghost:ButtonRole.Secondary;b.Selected=state=="Selected";b.Enabled=!state.StartsWith("Disabled");row.Controls.Add(b);if(state=="Hover")typeof(QuietButton).GetMethod("OnMouseEnter",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(b,[EventArgs.Empty]);if(state=="Pressed")typeof(QuietButton).GetMethod("OnMouseDown",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(b,[new MouseEventArgs(MouseButtons.Left,1,5,5,0)]);}
     states.Show();SendMessage(states.Handle,0x127,new IntPtr(0x10002),IntPtr.Zero);row.Controls[^1].Focus();await Capture(states,"interaction-states");var focusButton=(QuietButton)row.Controls[row.Controls.Count-1];using(var proof=new Bitmap(focusButton.Width,focusButton.Height)){focusButton.DrawToBitmap(proof,new Rectangle(Point.Empty,focusButton.Size));int ringPixels=0;for(int y=0;y<proof.Height;y++)for(int x=0;x<proof.Width;x++)if(proof.GetPixel(x,y).ToArgb()==Theme.Accent.ToArgb())ringPixels++;Check("Keyboard focus cue native pixels",focusButton.Focused&&focusButton.VisualState=="focus"&&ringPixels>10,new{focusButton.Focused,focusButton.VisualState,ringPixels});}var disabled=row.Controls.OfType<QuietButton>().Single(b=>b.Text=="Disabled primary");using(var proof=new Bitmap(disabled.Width,disabled.Height)){disabled.DrawToBitmap(proof,new Rectangle(Point.Empty,disabled.Size));var pixel=proof.GetPixel(proof.Width/2,8);Check("Disabled primary subdued native fill",!disabled.Enabled&&pixel.B<160,new{pixel.R,pixel.G,pixel.B});}Check("Button state differentiation",row.Controls.OfType<QuietButton>().Any(b=>b.VisualState=="hover")&&row.Controls.OfType<QuietButton>().Any(b=>b.VisualState=="pressed"));states.Close();}
    using(var s=Fixture("topmost","NONE")){using var app=new Form{Text="Native foreground fixture",Width=800,Height=600};using var edit=new TextBox{Dock=DockStyle.Fill,Multiline=true};app.Controls.Add(edit);app.Show();using var hud=new OverlayForm(s,true);hud.Show();hud.ApplySettings();SetActiveWindow(app.Handle);edit.Focus();var focus=GetFocus();int before=hud.TopMostReassertCount;NotifyWinEvent(3,app.Handle,0,0);for(int i=0;i<10&&hud.TopMostReassertCount==before;i++)await Task.Delay(100);Check("WinEvent foreground reassert",hud.ForegroundHookInstalled&&hud.TopMostReassertCount>before);Check("No keyboard focus theft",GetFocus()==focus&&GetActiveWindow()==app.Handle&&hud.LastTopMostFlags==(1u|2u|16u));app.WindowState=FormWindowState.Maximized;Check("Maximize reassert",hud.ReassertTopMostForTest(app.Handle));app.WindowState=FormWindowState.Minimized;app.WindowState=FormWindowState.Normal;Check("Restore reassert",hud.ReassertTopMostForTest(app.Handle));hud.ToggleMode();hud.ToggleMode();hud.Hide();Check("Hidden no reassert",!hud.ReassertTopMostForTest(app.Handle));hud.Reveal();Check("Reveal topmost style",(GetWindowLong(hud.Handle,-20)&8)!=0);s.Settings.TopMost=false;hud.ApplySettings();Check("Topmost OFF native style",!hud.ReassertTopMostForTest(app.Handle)&&(GetWindowLong(hud.Handle,-20)&8)==0);s.Settings.TopMost=true;hud.ApplySettings();Check("Topmost ON native style",(GetWindowLong(hud.Handle,-20)&8)!=0);hud.Close();app.Close();}
    using(var s=Fixture("high-contrast","NONE")){using var page=new SettingsForm(s);page.Show();await Pump();Theme.TestHighContrast=true;Theme.RefreshPalette(page);await Capture(page,"settings-high-contrast");Check("High contrast follows system colors",page.BackColor==SystemColors.Window);var close=page.AllControls().OfType<R2WindowButton>().Single(x=>x.Text=="×");typeof(Control).GetMethod("OnMouseEnter",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(close,[EventArgs.Empty]);await Capture(page,"settings-high-contrast-close-hover");using(var bitmap=new Bitmap(close.Width,close.Height)){close.DrawToBitmap(bitmap,new Rectangle(Point.Empty,close.Size));int glyph=0;for(int y=0;y<bitmap.Height;y++)for(int x=0;x<bitmap.Width;x++)if(bitmap.GetPixel(x,y).ToArgb()==SystemColors.HighlightText.ToArgb())glyph++;Check("High contrast close hover glyph visible",glyph>5&&bitmap.GetPixel(2,2).ToArgb()==SystemColors.Highlight.ToArgb(),new{glyph});}Theme.TestHighContrast=false;Theme.RefreshPalette(page);Check("High contrast restores dark palette",page.BackColor==Theme.Canvas);page.Close();Theme.TestHighContrast=null;}
    Check("Bilingual resources resolved",L.Missing.Count==0,L.Missing.Keys.ToArray());
    }
   }catch(Exception ex){failed++;File.WriteAllText(Path.Combine(output,"error.txt"),ex.ToString());}
   finally{AtomicJson.Save(Path.Combine(output,"complete.json"),new{exe_sha256=ReportExporter.ExeHash(),total=checks.Count,failed,frames,classification="NATIVE_PRIVATE_DESKTOP_SYNTHETIC_FIXTURES",limitations=new[]{"No Codex foreground or physical Alt+Tab on Human input desktop","Windows 11 physical device not tested"}});Environment.ExitCode=failed==0?0:1;main.Close();Application.Exit();}
  };
 }
}
